### ISSUE TITLE
How to train the BPE codes and vocab?

### ISSUE THREAD

**Issue by zyuuyuu** [facebookresearch/XLM#102]
I used the XNLI15 model for a classification task and obtained very good results. Thank you for the good work!

Now I want the model to be able to handle languages such as Portuguese, Italian and Japanese. Even though for those languages share some vocabulary with the existing XNLI15 languages, but I wanna try and see how the performances will improve with vocab and codes including the new languages. 

I'm just wondering on what data you guys train the XNLI15 vocab and codes, so that I could compare the performance with the existing model.

Thanks!

**Comment by aconneau** [comment]
For XNLI15, we took ~100M tokens (coming from sentences randomly sampled) in each Wikipedia, we concatenated and learned our shared BPE on that. When some languages do not have enough data, we duplicate lines from the Wikipedia to balance the presence of the languages in the BPE training set.

**Comment by jind11** [comment]
Could you share the script for learning the BPE codes and vocabs for the 15 languages? In the original paper, it is said that there is a sampling strategy, which I cannot fully understand. Thanks!

**Comment by aconneau** [comment]
The shared vocabulary of the 15 languages after BPE-zation can be found in the [README](https://github.com/facebookresearch/XLM#pretrained-models).

Below is the script I used to downsample the importance of high-resource languages in the creation of the BPE vocabulary. It takes as input the "$lg.train" files (e.g. en.train, th.train, fr.train etc), and outputs a training set for BPE "bpe.train[..]", on top of which you should run [fastBPE](https://github.com/glample/fastBPE). 

```bash
# Command line example
lgs="ar-bg-de-el-en-es-fr-hi-ru-sw-th-tr-ur-vi-zh"
python get_bpe_train_ranking.py --S 0.5 --scale 1e4 --lgs $lgs --debug
```

```python
"""
get_bpe_train_ranking.py
Get bpe training set from "$lg.train" files of several languages
"""
import os
import numpy as np
import argparse

parser = argparse.ArgumentParser(description='Creation of bpe.train')
parser.add_argument("--S", type=float, default=0.5, help="exponent subsampling factor")
parser.add_argument("--lgs", type=str, default="", help="list of languages hyphen-separated")
parser.add_argument("--scale", type=float, default=1e4, help="controls the minimum number of sentences of each language")
parser.add_argument('--debug', dest='debug', action='store_true')
parser.set_defaults(debug=False)

params = parser.parse_args()

# get the number of words in the corpus of each language 
# lg2count.txt -> tsv file: first column is language (e.g. "en", or "fr") and second column is number of lines
lg2count = {}
with open('lg2count.txt') as f:
    for line in f:
        line = line.rstrip().split('\t')
        lg, count = line[0], int(line[1])
        lg2count[lg] = count
        assert lg2count[lg] > 0, lg

# downsample (S < 1) or upsample (S>1) the importance of high-resource languages
S = params.S
tot = sum([lg2count[lg] for lg in lg2count])
tot_S = sum([lg2count[lg]**S for lg in lg2count])
if params.debug:
    for lg in lg2count:
        print('%s - before resampling: %.2f - after resampling: %.2f' % (lg, 100.0 * lg2count[lg] / tot, 100.0 * lg2count[lg]**S / tot_S))

# minimum count and minimum probability
min_c = min([lg2count[lg] for lg in lg2count])
min_p = min([lg2count[lg]**S for lg in lg2count]) / tot_S

# scale:
for lg in params.lgs.split('-'):
    p = lg2count[lg]**S / tot_S
    # print('%s : %.0f' % (lg, params.scale * min_c * (p / min_p)))
    COMMAND = "shuf -r -n %.0f %s.train >> bpe.train.factor=%s" % (scale * min_c * (p / min_p), lg, params.S)
    if params.debug:
        print(COMMAND)
    else:
        os.system(COMMAND)
```

**Comment by aconneau** [comment]
Closing the issue, feel free to re-open if needed.
