### ISSUE TITLE
Fine tuning with language id

### ISSUE THREAD

**Issue by thies1006** [facebookresearch/XLM#103]
I was fine tuning a classifier and the model worked well for different languages. But what surprised me was that it is not necessary to specify the language id when predicting. 

It seems that also during training the language id isn't passed to the model:
https://github.com/facebookresearch/XLM/blob/master/src/evaluation/glue.py#L165

Wouldn't it be better to train/predict with the language id included?

**Comment by glample** [comment]
Correct, it should be better if the language is included. But we usually evaluate on GLUE models trained only in English, and for models trained on only one language, the model does not have any language embedding lookup table, and the `langs` parameter has to be set to None, so it will not make any difference. But if you evaluate on GLUE a model that handles different languages, it will work better to give the language identifier as input (this is maybe something we should enforce in the code actually).

**Comment by glample** [comment]
Actually, we had some bug in the code initially, and we forgot to give the language ID as input for XNLI evaluation. This was hurting the performance quite significantly. So be sure to give the language ID for cross-lingual models.

**Comment by thies1006** [comment]
Ok, thank you very much for clarification.
