### ISSUE TITLE
subsample the frequent outputs using an approach similar to Mikolov et al. (2013b)

### ISSUE THREAD

**Issue by donglixp** [facebookresearch/XLM#104]
Nice work! I noticed that the paper (https://arxiv.org/pdf/1901.07291.pdf) mentioned:

> To counter the imbalance between rare and frequent tokens (e.g. punctuations or stop words), we also subsample the frequent outputs using an approach similar to Mikolov et al. (2013b): tokens in a text stream are sampled according to a multinomial distribution, whose weights are proportional to the square root of their invert frequencies.

I tried to find the corresponding implementation in the repo. However, I didn't find them. A similar issue was also proposed in https://github.com/facebookresearch/XLM/issues/3 . It would be great if a pointer to the code could be given. Thanks!

**Comment by glample** [comment]
Hi, this corresponds to this part: https://github.com/facebookresearch/XLM/blob/master/src/trainer.py#L331-L341

**Comment by donglixp** [comment]
Thanks for the reply! @glample
