### ISSUE TITLE
BeamHypotheses might underperform

### ISSUE THREAD

**Issue by christopher5106** [facebookresearch/XLM#106]
Hi,

I'm wondering why `is_done` does not take the hypothese length
https://github.com/facebookresearch/XLM/blob/master/src/model/transformer.py#L714-L724

I would expect it to have the same arguments as the `add` method :
 ```
   def is_done(self, hyp, best_sum_logprobs):
        """
        If there are enough hypotheses and that none of the hypotheses being generated
        can become better than the worst one in the heap, then we are done with this sentence.
        """
        if len(self) < self.n_hyp:
            return False
        elif self.early_stopping:
            return True
        else:
            return self.worst_score >= best_sum_logprobs / len(hyp) ** self.length_penalty

```
Christopher

**Comment by glample** [comment]
Hi,

I'm not sure I see what you mean. `is_done` considers the hypothesis length with `len(hyp)` no?

**Comment by christopher5106** [comment]
no, it uses `self.max_len` which will stop it before being really done.

**Comment by glample** [comment]
Oh yeah my bad, I was looking at your code sorry. I think the current implementation is correct. It basically says that in the best possible scenario, where all remaining elements have a perfect probability score of 1 (so the sum of logprobs will not increase), then you will end up with the score `best_sum_logprobs / self.max_len ** self.length_penalty`.

But if this best possible score is worse than the current worst score, then we know we won't find a better hypothesis and we can stop here.

In the code you suggest, it is possible than the condition in the last line returns `True`, but that if you had done more decoding steps it would have returned `False`.

Does that make sense?

**Comment by christopher5106** [comment]
I'm not sure to get it.
Your hypothese score is `score = sum_logprobs / len(hyp) ** self.length_penalty`.
But in `is_done` method, you use a value that is smaller
`score = sum_logprobs / self.max_len ** self.length_penalty`
so the `is_done` method will return True more than it should, no ?

**Comment by christopher5106** [comment]
Your reasoning would work, if you had `sum_logprobs / (len(hyp)+1) ** self.length_penalty`, that is adding an element with perfect probability to the sequence but I  think that `sum_logprobs / self.max_len ** self.length_penalty` is far too low (you compare with the best case with all remaining elements, but you could have better cases adding a less elements elements with perfect probability - ie shorter sentences ) and this is sufficient to miss some cases I think.

**Comment by glample** [comment]
> I'm not sure to get it.
> Your hypothese score is `score = sum_logprobs / len(hyp) ** self.length_penalty`.
> But in `is_done` method, you use a value that is smaller
> `score = sum_logprobs / self.max_len ** self.length_penalty`
> so the `is_done` method will return True more than it should, no ?

Did you take into account the fact that the scores are negatives (sum of log probabilities)? which means that:
`sum_logprobs / self.max_len ** self.length_penalty`
will be smaller than:
`sum_logprobs / len(hyp) ** self.length_penalty`
Since `sum_logprobs` is negative, the best possible score you can get is 0, so by dividing `sum_logprobs` by the maximum length instead of the current hypothesis length you get a better score. Does that make sense? It's possible that I made a mistake but here I think this is correct.

**Comment by christopher5106** [comment]
Oups I missed that! You are right then.
