### ISSUE TITLE
Unable to run unsupervised MT on Multiple GPUs

### ISSUE THREAD

**Issue by Dolprimates** [facebookresearch/XLM#109]
I tried unsupervised MT on Multiple GPUs on the below command

`export CUDA_VISIBLE_DEVICES=2,7; export export NGPU=2; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py --exp_name unsupMT_enfr --dump_path ./dumped/ --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path ./data/processed/en-fr/ --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 2000 --batch_size 32 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu'`

and got below error

```
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupNCCL object at 0x7f0da5e05180>, [[tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0'), tensor([-0.0113,  0.0161,  0.0634,  ..., -0.0057, -0.0471,  0.0002],
       device='cuda:0'), None]], [0]
```

2GPUs are both "GeForce GTX TITAN X" and both have 12212 MB memory.

(I get below error when I just use one of the above GPUs.

`RuntimeError: CUDA out of memory. Tried to allocate 472.75 MiB (GPU 0; 11.93 GiB total capacity; 10.35 GiB already allocated; 208.81 MiB free; 897.06 MiB cached)`

Is it not enough with 12GB?

**Comment by glample** [comment]
This is an error that occurs with PyTorch distributed when some parameters are not updated, in that case the parameters of the encoder output layer are not updated since it's not a language modeling task anymore. This error will not happen with the last version of PyTorch. In the meantime, can you try to set `with_output=False` at the following line? https://github.com/facebookresearch/XLM/blob/master/src/model/__init__.py#L127

**Comment by Dolprimates** [comment]
I tried but got a different error.

RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Unexpected key(s) in state_dict: "pred_layer.proj.weight", "pred_layer.proj.bias".

**Comment by Dolprimates** [comment]
As I installed the last version of PyTorch, I got a different error again.

`subprocess.CalledProcessError: Command '['**mypath**/.pyenv/versions/3.6.8/bin/python', '-u', 'train.py', '--local_rank=0', '--exp_name', 'unsupMT_enfr', '--dump_path', './dumped/', '--reload_model', 'mlm_enfr_1024.pth,mlm_enfr_1024.pth', '--data_path', './data/processed/en-fr/', '--lgs', 'en-fr', '--ae_steps', 'en,fr', '--bt_steps', 'en-fr-en,fr-en-fr', '--word_shuffle', '3', '--word_dropout', '0.1', '--word_blank', '0.1', '--lambda_ae', '0:1,100000:0.1,300000:0', '--encoder_only', 'false', '--emb_dim', '1024', '--n_layers', '6', '--n_heads', '8', '--dropout', '0.1', '--attention_dropout', '0.1', '--gelu_activation', 'true', '--tokens_per_batch', '2000', '--batch_size', '32', '--bptt', '256', '--optimizer', 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001', '--epoch_size', '200000', '--eval_bleu', 'true', '--stopping_criterion', 'valid_en-fr_mt_bleu,10', '--validation_metrics', 'valid_en-fr_mt_bleu']' returned non-zero exit status 1.`

**Comment by glample** [comment]
The first error can be addressed by setting `strict=False` in the `load_state_dict` functions of the same file. Sorry about that, it's not very convenient and we will try to make this a bit more flexible.

I don't understand the second error, the problem does not seem to come from the codebase though.

**Comment by glample** [comment]
Regarding the first error and `strict=False`: https://pytorch.org/tutorials/beginner/saving_loading_models.html#id4

**Comment by Dolprimates** [comment]
which does "2nd error" means, `dist._dist_broadcast_coalesced` or `subprocess.CalledProcessError` ?

**Comment by glample** [comment]
I meant `subprocess.CalledProcessError`. `dist._dist_broadcast_coalesced` is the distributed error that happens with previous versions of PyTorch where you need to have updated on all parameters.

**Comment by Dolprimates** [comment]
`subprocess.CalledProcessError`

seems to be coming from below error. (I get this error from each GPU.)

```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its ou
tput (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. I
f you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please includ
e the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cp
p:408)
```

I'm new to the pytorch (also NLP), so I'm not familiar.

**Comment by teslacool** [comment]
@Dolprimates  I encountered the same problem, you just need to
1. change to `encoder = TransformerModel(params, dico, is_encoder=True, with_output=False) ` at [line](https://github.com/facebookresearch/XLM/blob/03d7e94e04abeb238a4b7b76d78417e96016cba1/src/model/__init__.py#L127).
2. change to `encoder.load_state_dict(enc_reload, strict=False)` at [line](https://github.com/facebookresearch/XLM/blob/03d7e94e04abeb238a4b7b76d78417e96016cba1/src/model/__init__.py#L148).

I hope this can help you.

**Comment by Dolprimates** [comment]
@teslacool  Thank you!  Solved the issue.
But, don't these changes affect the final result?

**Comment by teslacool** [comment]
@Dolprimates It will not affect your all NMT experiments. Because the encoder does not need to predict something.

**Comment by Dolprimates** [comment]
How about MLM?
Don't these changes affect MLM experiment?

**Comment by glample** [comment]
In MLM you don't have any decoder, and you need to set `with_output=True` because the predictions are done on top of the encoder (the code will break anyway if there is something wrong).
