### ISSUE TITLE
Bug with file path in get-data-xnli.sh

### ISSUE THREAD

**Issue by rajenchatterjee** [facebookresearch/XLM#11]
Hi, There were couple of bugs in the "get-data-xnli.sh" script related to file path. The following is the fix:

1) comment "mkdir -p $XNLI_PATH" (line 29) -- creating this directory prevents downloading XNLI-1.0.zip
 
2) replace 
                 mkdir -p $PROCESSED_PATH/eval/XNLI
                 rm $PROCESSED_PATH/eval/XNLI/*.          -- getting error "cannot remove...no such file..."
    with
                 if [ -d $PROCESSED_PATH/eval/XNLI ]; then
                     rm -rf $PROCESSED_PATH/eval/XNLI
                 fi
                 mkdir -p $PROCESSED_PATH/eval/XNLI

**Comment by glample** [comment]
Hi, thanks for finding this. I pushed https://github.com/facebookresearch/XLM/commit/d2289e398f52c8ca15c440bf10199287d8d2551c this should fix 2).
I don't understand the issue in 1) though, why does it prevent the download?

**Comment by rajenchatterjee** [comment]
for 1: I guess, because the XNLI-1.0.zip file will be downloaded if there is no directory with the name "$OUTPATH/XNLI-1.0", however, the command "mkdir -p $XNLI_PATH" (which is executed before downloading the zip file) already creates an empty directory 
(NB: $XNLI_PATH is same as $OUTPATH/XNLI-1.0)

**Comment by glample** [comment]
Ah, you are right, thanks. This commit fixes that, among other things: https://github.com/facebookresearch/XLM/commit/2dc4b8fc745a3ae7a8f0f0eb7b8b18b0735ffd80
