### ISSUE TITLE
Replicating `XLM_en` results

### ISSUE THREAD

**Issue by bkj** [facebookresearch/XLM#112]
Are you able to share the hyperparameters used to train the monolingual `XLM_en` model?  I see some of the hyperparameters are included in the pretrained model, but it has some references to reloading from a checkpoints, etc.

Thanks!

**Comment by aconneau** [comment]
Hi,
we used the following parameters:

--n_heads 16 --bt_steps '' --max_vocab '-1' --word_mask_keep_rand '0.8,0.1,0.1' --word_blank 0 --n_layers 12 --eval_bleu false --max_len 200 --bptt 256 --fp16 true --share_inout_emb true --sinusoidal_embeddings false --word_shuffle 0 --tokens_per_batch 4000 --mlm_steps en --attention_dropout '0.1' --split_data false --max_epoch 100000 --stopping_criterion '_valid_en_mlm_ppl,25' --dump_path '/path/to/dump_folder' --epoch_size 300000 --gelu_activation true --data_path '/path/to/data' --optimizer 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.00020,weight_decay=0' --validation_metrics _valid_en_mlm_ppl --save_periodic 10 --dropout '0.1' --mt_steps '' --batch_size 32 --word_dropout 0 --reload_model '' --min_count 0 --group_by_size true --asm false --lg_sampling_factor '-1' --word_pred '0.15' --ae_steps '' --emb_dim 2048 --encoder_only true --lgs en --clm_steps '' --exp_name xlm_en_12_2048 --eval_only false

Thanks,
Alexis

**Comment by bkj** [comment]
Thanks!  That's super helpful.  One more question -- what kind of hardware did you use / roughly what was the wall clock time?

**Comment by aconneau** [comment]
Glad that helps. We might push some additional modifications that improve pretraining (just a few optimization tricks). I'll put the new set of 'good' parameters when that's the case. Hardware was 64 GPUs (V100), and it took around a couple of weeks of training at the time. Also, it's important to not trust the perplexity of the model on your valid set: usually the longer the training the better. Even when the ppl starts to plateau, the model generalization keeps improving up to a certain point.

**Comment by bkj** [comment]
OK thanks.  Interesting point about the ppl vs downstream generalization.

NVIDIA's [Megatron](https://github.com/NVIDIA/Megatron-LM) claims to train to the original accuracy of BERT in 3 days on 64xV100s, and Google's [BERT](https://github.com/google-research/bert) says it'll take 2 weeks on a single TPUv2.  So it sounds like `XLM_en` was quite a bit more expensive to train -- do you know why that may be?  Just curious -- I know these things aren't always apples-to-apples comparisons.

Thanks again!

**Comment by glample** [comment]
It is longer because the original BERT model is composed of 24 layers of dimension 1024, and not 12 layers of dimension 2048, so BERT model has 2x less parameters which requires less training iterations (and iterations are also faster since the model is smaller). Also, BERT and Nvidia uses Adam with a linear learning rate decay. In that setting, the number of iterations is predefined in advance (typically, 1 million steps). In our case we use an inverse sqrt decay as in the initial BERT model. This way the model never stops improving, and it's up to you to decide that it has converged and that you can stop training.

But as @aconneau said, we found that performance on downstream tasks kept improving even if perplexity was plateauing. But you can also stop after 1M steps and in that case the training time should be a bit less than 4 days with XLM and 24 layers dim 1024. Not sure how Nvidia can make it in 3 days, I guess they have optimizations we don't have, we will have a look.

**Comment by glample** [comment]
Actually, I'm not sure training is comparable. Looking at the code I think we have a quite larger number of tokens per batch. And they also have the next sentence prediction objective which you probably want to get rid of.

**Comment by bhardwaj1230** [comment]
Hello @glample ,

I am trying to train and test supervised MT model, I am using my NRC parallel corpus (en-fr).

Getting the below error, I have modified your "**get-data-nmt.sh**" file to get parallel data for (train,test and validate) , evaluating BPE and full_vocab from my parallel training corpus.
I am constantly getting the below error, and confused with what mistake I am making:

> 
> /opt/conda/conda-bld/pytorch_1549627089062/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = -1, SrcDim = -1, IdxDim = -1, IndexIsMajor = true]: block: [89,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /opt/conda/conda-bld/pytorch_1549627089062/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = -1, SrcDim = -1, IdxDim = -1, IndexIsMajor = true]: block: [89,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> /opt/conda/conda-bld/pytorch_1549627089062/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = -1, SrcDim = -1, IdxDim = -1, IndexIsMajor = true]: block: [89,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1549627089062/work/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=59 : device-side assert triggered
> Traceback (most recent call last):
>   File "train.py", line 330, in <module>
>     main(params)
>   File "train.py", line 305, in main
>     scores = evaluator.run_all_evals(trainer)
>   File "/u/bhardwas/bt/NMT/XLM/XLM/src/evaluation/evaluator.py", line 181, in run_all_evals
>     self.evaluate_mt(scores, data_set, lang1, lang2, eval_bleu)
>   File "/u/bhardwas/bt/NMT/XLM/XLM/src/evaluation/evaluator.py", line 386, in evaluate_mt
>     generated, lengths = decoder.generate(enc1, len1, lang2_id, max_len=max_len)
>   File "/u/bhardwas/bt/NMT/XLM/XLM/src/model/transformer.py", line 493, in generate
>     if unfinished_sents.max() == 0:
> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1549627089062/work/aten/src/THC/generated/../THCReduceAll.cuh:317
> 


Modified "**get-data-nmt.sh**"  file :

_

> # Copyright (c) 2019-present, Facebook, Inc.
> # All rights reserved.
> #
> # This source code is licensed under the license found in the
> # LICENSE file in the root directory of this source tree.
> #
> 
> set -e
> 
> 
> #
> # Data preprocessing configuration
> #
> CODES=60000     # number of BPE codes
> N_THREADS=16    # number of threads in data preprocessing
> 
> 
> #
> # Read arguments
> #
> POSITIONAL=()
> while [[ $# -gt 0 ]]
> do
> key="$1"
> case $key in
>   --src)
>     SRC="$2"; shift 2;;
>   --tgt)
>     TGT="$2"; shift 2;;
>   --reload_codes)
>     RELOAD_CODES="$2"; shift 2;;
>   --reload_vocab)
>     RELOAD_VOCAB="$2"; shift 2;;
>   *)
>   POSITIONAL+=("$1")
>   shift
>   ;;
> esac
> done
> set -- "${POSITIONAL[@]}"
> 
> 
> #
> # Check parameters
> #
> if [ "$SRC" == "" ]; then echo "--src not provided"; exit; fi
> if [ "$TGT" == "" ]; then echo "--tgt not provided"; exit; fi
> if [ "$SRC" != "de" -a "$SRC" != "en" -a "$SRC" != "fr" -a "$SRC" != "ro" ]; then echo "unknown source language"; exit; fi
> if [ "$TGT" != "de" -a "$TGT" != "en" -a "$TGT" != "fr" -a "$TGT" != "ro" ]; then echo "unknown target language"; exit; fi
> if [ "$SRC" == "$TGT" ]; then echo "source and target cannot be identical"; exit; fi
> if [ "$SRC" \> "$TGT" ]; then echo "please ensure SRC < TGT"; exit; fi
> if [ "$RELOAD_CODES" != "" ] && [ ! -f "$RELOAD_CODES" ]; then echo "cannot locate BPE codes"; exit; fi
> if [ "$RELOAD_VOCAB" != "" ] && [ ! -f "$RELOAD_VOCAB" ]; then echo "cannot locate vocabulary"; exit; fi
> if [ "$RELOAD_CODES" == "" -a "$RELOAD_VOCAB" != "" -o "$RELOAD_CODES" != "" -a "$RELOAD_VOCAB" == "" ]; then echo "BPE codes should be provided if and only if vocabulary is also provided"; exit; fi
> 
> 
> #
> # Initialize tools and data paths
> #
> 
> # main paths
> MAIN_PATH=$PWD
> TOOLS_PATH=$PWD/tools
> DATA_PATH=$PWD/data
> MONO_PATH=$DATA_PATH/mono
> PARA_PATH=$DATA_PATH/para
> PROC_PATH=$DATA_PATH/processed/$SRC-$TGT
> 
> # create paths
> mkdir -p $TOOLS_PATH
> mkdir -p $DATA_PATH
> mkdir -p $PARA_PATH
> mkdir -p $PROC_PATH
> 
> # moses
> MOSES=$TOOLS_PATH/mosesdecoder
> REPLACE_UNICODE_PUNCT=$MOSES/scripts/tokenizer/replace-unicode-punctuation.perl
> NORM_PUNC=$MOSES/scripts/tokenizer/normalize-punctuation.perl
> REM_NON_PRINT_CHAR=$MOSES/scripts/tokenizer/remove-non-printing-char.perl
> TOKENIZER=$MOSES/scripts/tokenizer/tokenizer.perl
> INPUT_FROM_SGM=$MOSES/scripts/ems/support/input-from-sgm.perl
> 
> # fastBPE
> FASTBPE_DIR=$TOOLS_PATH/fastBPE
> FASTBPE=$TOOLS_PATH/fastBPE/fast
> 
> 
> # BPE / vocab files
> BPE_CODES=$PROC_PATH/codes
> SRC_VOCAB=$PROC_PATH/vocab.$SRC
> TGT_VOCAB=$PROC_PATH/vocab.$TGT
> FULL_VOCAB=$PROC_PATH/vocab.$SRC-$TGT
> 
> 
> # train / valid / test parallel BPE data
> PARA_SRC_TRAIN_BPE=$PROC_PATH/train.$SRC-$TGT.$SRC
> PARA_TGT_TRAIN_BPE=$PROC_PATH/train.$SRC-$TGT.$TGT
> PARA_SRC_VALID_BPE=$PROC_PATH/valid.$SRC-$TGT.$SRC
> PARA_TGT_VALID_BPE=$PROC_PATH/valid.$SRC-$TGT.$TGT
> PARA_SRC_TEST_BPE=$PROC_PATH/test.$SRC-$TGT.$SRC
> PARA_TGT_TEST_BPE=$PROC_PATH/test.$SRC-$TGT.$TGT
> 
> # train / valid / test file raw data
> unset PARA_SRC_TRAIN PARA_TGT_TRAIN PARA_SRC_VALID PARA_TGT_VALID PARA_SRC_TEST PARA_TGT_TEST
> if [ "$SRC" == "en" -a "$TGT" == "fr" ]; then
>   PARA_SRC_TRAIN=/u/bhardwas/bt/bt_dump/train_bt_en
>   PARA_TGT_TRAIN=/u/bhardwas/bt/bt_dump/train_bt_fr
>   PARA_SRC_VALID=/u/bhardwas/bt/bt_dump/valid_bt_en
>   PARA_TGT_VALID=/u/bhardwas/bt/bt_dump/valid_bt_fr
>   PARA_SRC_TEST=/u/bhardwas/bt/bt_dump/test_bt_en
>   PARA_TGT_TEST=/u/bhardwas/bt/bt_dump/test_bt_fr
> fi
> 
> 
> # install tools
> ./install-tools.sh
> 
> SRC_PREPROCESSING="$REPLACE_UNICODE_PUNCT | $NORM_PUNC -l $SRC | $REM_NON_PRINT_CHAR | $TOKENIZER -l $SRC -no-escape -threads $N_THREADS"
> TGT_PREPROCESSING="$REPLACE_UNICODE_PUNCT | $NORM_PUNC -l $TGT | $REM_NON_PRINT_CHAR | $TOKENIZER -l $TGT -no-escape -threads $N_THREADS"
> 
> echo "Tokenizing training data..."
> 
> eval "cat $PARA_SRC_TRAIN | $SRC_PREPROCESSING > $PARA_SRC_TRAIN.all"
> eval "cat $PARA_TGT_TRAIN | $TGT_PREPROCESSING > $PARA_TGT_TRAIN.all"
> 
> 
> # reload BPE codes
> cd $MAIN_PATH
> if [ ! -f "$BPE_CODES" ] && [ -f "$RELOAD_CODES" ]; then
>   echo "Reloading BPE codes from $RELOAD_CODES ..."
>   cp $RELOAD_CODES $BPE_CODES
> fi
> 
> # learn BPE codes
> if [ ! -f "$BPE_CODES" ]; then
>   echo "Learning BPE codes..."
>   $FASTBPE learnbpe $CODES $PARA_SRC_TRAIN.all $PARA_TGT_TRAIN.all > $BPE_CODES
> fi
> echo "BPE learned in $BPE_CODES"
> 
> echo "Applying BPE to training files..."
> 
> # apply BPE codes
> if ! [[ -f "$PARA_SRC_TRAIN_BPE" ]]; then
>   echo "Applying $SRC BPE codes..."
>   $FASTBPE applybpe $PARA_SRC_TRAIN_BPE $PARA_SRC_TRAIN.all $BPE_CODES
> fi
> if ! [[ -f "$PARA_TGT_TRAIN_BPE" ]]; then
>   echo "Applying $TGT BPE codes..."
>   $FASTBPE applybpe $PARA_TGT_TRAIN_BPE $PARA_TGT_TRAIN.all $BPE_CODES
> fi
> echo "BPE codes applied to $SRC in: $PARA_SRC_TRAIN_BPE"
> echo "BPE codes applied to $TGT in: $PARA_TGT_TRAIN_BPE"
> 
> 
> echo "Binarizing data..."
> rm -f $PARA_SRC_TRAIN_BPE.pth $PARA_TGT_TRAIN_BPE.pth $PARA_SRC_VALID_BPE.pth $PARA_TGT_VALID_BPE.pth $PARA_SRC_TEST_BPE.pth $PARA_TGT_TEST_BPE.pth
> 
> 
> # extract source and target vocabulary
> if ! [[ -f "$SRC_VOCAB" && -f "$TGT_VOCAB" ]]; then
>   echo "Extracting vocabulary..."
>   $FASTBPE getvocab $PARA_SRC_TRAIN_BPE > $SRC_VOCAB
>   $FASTBPE getvocab $PARA_TGT_TRAIN_BPE > $TGT_VOCAB
> fi
> echo "$SRC vocab in: $SRC_VOCAB"
> echo "$TGT vocab in: $TGT_VOCAB"
> 
> # reload full vocabulary
> cd $MAIN_PATH
> if [ ! -f "$FULL_VOCAB" ] && [ -f "$RELOAD_VOCAB" ]; then
>   echo "Reloading vocabulary from $RELOAD_VOCAB ..."
>   cp $RELOAD_VOCAB $FULL_VOCAB
> fi
> 
> # extract full vocabulary
> if ! [[ -f "$FULL_VOCAB" ]]; then
>   echo "Extracting vocabulary..."
>   $FASTBPE getvocab $PARA_SRC_TRAIN_BPE $PARA_TGT_TRAIN_BPE > $FULL_VOCAB
> fi
> echo "Full vocab in: $FULL_VOCAB"
> 
> #
> # Process parallel data
> #
> 
> cd $PARA_PATH
> 
> # check valid and test files are here
> 
> if ! [[ -f "$PARA_SRC_VALID" ]]; then echo "$PARA_SRC_VALID is not found!"; exit; fi
> if ! [[ -f "$PARA_TGT_VALID" ]]; then echo "$PARA_TGT_VALID is not found!"; exit; fi
> if ! [[ -f "$PARA_SRC_TEST" ]];  then echo "$PARA_SRC_TEST is not found!";  exit; fi
> if ! [[ -f "$PARA_TGT_TEST" ]];  then echo "$PARA_TGT_TEST is not found!";  exit; fi
> 
> # tokenize data
> 
> echo "Tokenizing training data..."
> 
> eval "cat $PARA_SRC_VALID | $SRC_PREPROCESSING > $PARA_SRC_VALID.all"
> eval "cat $PARA_TGT_VALID | $TGT_PREPROCESSING > $PARA_TGT_VALID.all"
> eval "cat $PARA_SRC_TEST | $SRC_PREPROCESSING > $PARA_SRC_TEST.all"
> eval "cat $PARA_TGT_TEST | $TGT_PREPROCESSING > $PARA_TGT_TEST.all"
> 
> echo "Applying BPE to training, valid and test files..."
> 
> #EDIT:
> 
> $FASTBPE applybpe $PARA_SRC_VALID_BPE $PARA_SRC_VALID.all $BPE_CODES
> $FASTBPE applybpe $PARA_TGT_VALID_BPE $PARA_TGT_VALID.all $BPE_CODES
> $FASTBPE applybpe $PARA_SRC_TEST_BPE  $PARA_SRC_TEST.all  $BPE_CODES
> $FASTBPE applybpe $PARA_TGT_TEST_BPE  $PARA_TGT_TEST.all  $BPE_CODES
> 
> 
> echo "Binarizing data..."
> rm -f $PARA_SRC_TRAIN_BPE.pth $PARA_TGT_TRAIN_BPE.pth $PARA_SRC_VALID_BPE.pth $PARA_TGT_VALID_BPE.pth $PARA_SRC_TEST_BPE.pth $PARA_TGT_TEST_BPE.pth
> 
> 
> # binarize data
> if ! [[ -f "$PARA_SRC_TRAIN_BPE.pth" ]]; then
>   echo "Binarizing $SRC data..."
>   $MAIN_PATH/preprocess.py $FULL_VOCAB $PARA_SRC_TRAIN_BPE
> fi
> if ! [[ -f "$PARA_TGT_TRAIN_BPE.pth" ]]; then
>   echo "Binarizing $TGT data..."
>   $MAIN_PATH/preprocess.py $FULL_VOCAB $PARA_TGT_TRAIN_BPE
> fi
> echo "$SRC binarized data in: $PARA_SRC_TRAIN_BPE.pth"
> echo "$TGT binarized data in: $PARA_TGT_TRAIN_BPE.pth"
> 
> $MAIN_PATH/preprocess.py $FULL_VOCAB $PARA_SRC_VALID_BPE
> $MAIN_PATH/preprocess.py $FULL_VOCAB $PARA_TGT_VALID_BPE
> $MAIN_PATH/preprocess.py $FULL_VOCAB $PARA_SRC_TEST_BPE
> $MAIN_PATH/preprocess.py $FULL_VOCAB $PARA_TGT_TEST_BPE
> 
> 
> #
> # Summary
> #
> echo ""
> echo "===== Data summary"
> echo "Parallel validation data:"
> echo "    $SRC: $PARA_SRC_TRAIN_BPE.pth"
> echo "    $TGT: $PARA_TGT_TRAIN_BPE.pth"
> echo "Parallel validation data:"
> echo "    $SRC: $PARA_SRC_VALID_BPE.pth"
> echo "    $TGT: $PARA_TGT_VALID_BPE.pth"
> echo "Parallel test data:"
> echo "    $SRC: $PARA_SRC_TEST_BPE.pth"
> echo "    $TGT: $PARA_TGT_TEST_BPE.pth"
> echo ""

_

**Comment by KelleyYin** [comment]
@bhardwaj1230 You can download the parallel corpus from the [link](https://github.com/pytorch/fairseq/tree/master/examples/scaling_nmt). Then use the codes and vocab opened here to process the corpus.
