### ISSUE TITLE
./get-data-para.sh  de-en

### ISSUE THREAD

**Issue by tuyu95** [facebookresearch/XLM#114]
I'd like to see the format of the files after get-data-para.sh, so that I can add my preprocessed data to the model. When I try to run ./get-data-para.sh  de-en, the error is below:

`--2019-06-27 15:38:49--  https://object.pouta.csc.fi/OPUS-EUbookshop/v2/moses/de-en.txt.zip
Resolving object.pouta.csc.fi (object.pouta.csc.fi)... 86.50.254.1, 86.50.254.0
Connecting to object.pouta.csc.fi (object.pouta.csc.fi)|86.50.254.1|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

The file is already fully retrieved; nothing to do.

Archive:  /home/s1852803/unmt/XLM/data/para/download.php?f=EUbookshop%2Fde-en.txt.zip
shuf: <(get_seeded_random 42): No such file or directory
head: unrecognized option '--977'
`

**Comment by aconneau** [comment]
Try to remove the file in XLM/data/para/ corresponding to de-en and retry? It works fine on both my Mac and my server. It seems that you've already downloaded that file?

**Comment by aconneau** [comment]
Hmm so it seems to come from the "split_data()" function, and what is weird is that either the "$NVAL" or "$NTRAIN" parameters seem to start with a "-" in your case, causing the "-$NVAL" or "-$NTRAIN" to be equal to "--977" which is an unrecognized option for "head" as there is two dashes.

Can you check if your data has been well downloaded? If so, could you output the value of "$NTRAIN" and "$NVAL" using "echo $NTRAIN" for instance in line 199?

Thanks

**Comment by tuyu95** [comment]
Hi, thanks a lot for your reply. By using your approach, I found a issue that some dataset is not full. However, after I sloved this problem, it still has some errors. I got the three numbers by using echo $NLINES, echo $NTRAIN, echo $NVAL. It seems normal. But the error says that "Assertion `splits.size() == 3' failed.", which may be caused by the failture of spliting the training, valid and test data.

144127
134127
139127
shuf: <(get_seeded_random 42): No such file or directory
shuf: <(get_seeded_random 42): No such file or directory
shuf: <(get_seeded_random 42): No such file or directory
144127
134127
139127
shuf: <(get_seeded_random 42): No such file or directory
shuf: <(get_seeded_random 42): No such file or directory
shuf: <(get_seeded_random 42): No such file or directory
Loading codes from /home/s1852803/unmt/XLM/guen.bpe ...
fast: fastBPE/fastBPE.hpp:455: void fastBPE::readCodes(const char*, std::unordered_map<std::pair<std::basic_string<char>, std::basic_string<char> >, unsigned int, fastBPE::pair_hash>&, std::unordered_map<std::basic_string<char>, std::pair<std::basic_string<char>, std::basic_string<char> > >&): Assertion `splits.size() == 3' failed.
get-data-para.sh: line 262: 140039 Aborted                 $FASTBPE applybpe $PROCESSED_PATH/$pair.$lg.$split $PARA_PATH/$pair.$lg.$split $CODES_PATH

**Comment by tuyu95** [comment]
I've found the problem. It is because I used another BPE version, so the vocab is a bit different from the fastBPE. After I retrain the fastBPE, the problem is solved. Thanks a lot!
