### ISSUE TITLE
How to pretrain with MLM and TLM using other languages

### ISSUE THREAD

**Issue by tuyu95** [facebookresearch/XLM#116]
Hello, in the guide of _pretrain a model with MLM_, it is said that _"If parallel data is available, the TLM objective can be used with --mlm_steps 'en-fr'. To train with both the MLM and TLM objective, you can use --mlm_steps 'en,fr,en-fr'. "_ 

Now I'm trying to add some parallel data into the pretrain (but I do not consider to train a XLIN model, just want to pretrain a better model, and then train a NMT model). After I adding some parallel data by _using get-data-para.sh_, I pretrain it following the guide, and the error seems that ...path is not a file. So I think that's because I don't put the files into a correct path for MLM+TLM pretrain. Actually I consider the guide of _Pretrain a language model (with MLM and TLM)_, and put the monoligual data into the XLM15, and also change their name into the format of what _get-data-wiki.sh_ outputs.

Therefore, my question is that if I want to pretrain a model with MLM and TLM, what should I do? I'm now dealing with Gujarati-English, so I cannot simply use the _get-data-xlin.sh_.

**Comment by aconneau** [comment]
Hello, you should have your files {train,valid,test}.{gu,en}.pth in the path specified by "--datapath" similar to [here](https://github.com/facebookresearch/XLM#pretrain-a-language-model-with-mlm-and-tlm). Then run the command line, specifying the right "mlm_steps".

**Comment by tuyu95** [comment]
Thanks a lot! I have found the right path and format of name, and now it works!
