### ISSUE TITLE
slurm job multi-GPU not working...

### ISSUE THREAD

**Issue by BinWone** [facebookresearch/XLM#118]
when i submit a slurm one node mulit-GPU jobs like this:
submit.sh
![image](https://user-images.githubusercontent.com/11994164/60669994-399d2000-9ea2-11e9-9284-8de8c10ac8ad.png)

run_slurm.sh
![image](https://user-images.githubusercontent.com/11994164/60669838-e62ad200-9ea1-11e9-8540-fcea1b80c6b7.png)

i set using 8GPUs, but just 1 GPU are runing, why?
![image](https://user-images.githubusercontent.com/11994164/60669914-09ee1800-9ea2-11e9-9fe2-ed84a5a2c6ca.png)

**Comment by glample** [comment]
Have a look at this part of the code https://github.com/facebookresearch/XLM/blob/master/src/slurm.py#L60-L102 and be sure that the code is running this when you run a SLURM job. You may have to change the code a bit to adapt it to your cluster.
