### ISSUE TITLE
truecasing

### ISSUE THREAD

**Issue by maxdel** [facebookresearch/XLM#12]
Hi, 

did you do truecasing/lowercasing in your MT experiments? From the code I can't find any signs of this. 

Is there any specific reason to do / not do it?

Thanks

**Comment by glample** [comment]
Hi,

No, we never used truecasing / lowercasing. This was quite popular in PBSMT models, but for NMT the best is to use BPE. BPE are typically applied on sentences with regular casing.

**Comment by glample** [comment]
We used lowercasing + BPE for XNLI though, as in this case the task is to do sentence classification, and the casing is not very useful. But in MT, where you need to generate, it's good to directly generate the good casing and BPE does this very well.

**Comment by maxdel** [comment]
@glample Moses truecasing only modifies the case of the 1st word in a sentence, with exception of things like Named Entities. This is to reduce the scarcity of your vocabulary (why to have both "Starting" and "starting" in the vocab?).

With BPE you have the same issue with the 1st wordpice of the 1st word (e.g. _start_ _ing_ vs _Start_ _ing_).

**Comment by glample** [comment]
Yes you could use truecasing in combination with BPE, but probably it wouldn't make a big difference. Also it's nice to limit the number of preprocessing steps in practice, I guess this is also why people don't use truecasing anymore. But it wouldn't hurt to use it for sure.

**Comment by maxdel** [comment]
@glample I didn't catch that people don't use truecasing anymore, so will look more into it. Thanks for pointing out!
