### ISSUE TITLE
Can XLM handle text without language type?

### ISSUE THREAD

**Issue by airkid** [facebookresearch/XLM#120]
Hi, I'm doing a project in which input texts are multilingual  and I'd like to do experiments by XLM.  
This is a universal project without language detection module, can XLM handle this issue?

**Comment by glample** [comment]
Yes, you can either apply a language detection classifier on your sentences (using fastText or something) or merge all corpora into a single file, and use XLM with a single language (even though there are many languages).

**Comment by airkid** [comment]
Thanks so much for your reply! It really helps me a lot.
