### ISSUE TITLE
How to do NMT inference

### ISSUE THREAD

**Issue by Panshangka** [facebookresearch/XLM#123]
Hello, after I finish the unsupervised training process in the en-fr example you showed us in this repo, how can I do inference? means translate english sentence to french. Can you give me a example command, thanks

**Comment by glample** [comment]
Hi,

You can have a look at this file with the example command: https://github.com/facebookresearch/XLM/blob/master/translate.py#L11-L15

**Comment by Anwarvic** [comment]
When I tried using the en-fr model you uploaded to the [README](https://github.com/facebookresearch/XLM#pretrained-xlmmlm-models) by running the [suggest command](https://github.com/facebookresearch/XLM/blob/master/translate.py#L11-L15), it throws the following error:
```
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main(params)
  File "translate.py", line 71, in main
    setattr(params, name, getattr(model_params, name))
AttributeError: 'AttrDict' object has no attribute 'bos_index'
```

**Comment by Anwarvic** [comment]
@klauspa did that work?!
