### ISSUE TITLE
Replicate the XNLI Result

### ISSUE THREAD

**Issue by cocaer** [facebookresearch/XLM#129]
The glue-xnli.py was changed and added two extra parameters—optimizer_e and optimizer_p while the readme suggests `optimizer adam,lr=0.000005`.
If I want to reproduce  the XNLI  result,  how can I set this new parameters?
By the way, does the batch_size play a important role because my machine only supports batch_size=8.

**Comment by aconneau** [comment]
I should fix the README problem there: 51886419f947d58aa02a19e6215e60bc1107b835
batch_size=8 will work fine, I swept with batch_size \in [4,8]
