### ISSUE TITLE
Question about generate-embeddings.ipynb

### ISSUE THREAD

**Issue by airkid** [facebookresearch/XLM#130]
Hi, I'm reading this project and I have a question about this line.
https://github.com/facebookresearch/XLM/blob/51886419f947d58aa02a19e6215e60bc1107b835/generate-embeddings.ipynb#L142
Since `BOS_WORD = '<s>'`, should this line be `<s> %s </s>` instead of `</s> %s </s>`? Thanks!

**Comment by glample** [comment]
Hi,

No, we used </s> everywhere for simplicity. This allows to train with stream of sentences separated by just a </s>. The <s> symbol is not used anywhere.
