### ISSUE TITLE
Not train values.weight

### ISSUE THREAD

**Issue by jingweiz** [facebookresearch/XLM#134]
Hi,
I saw that you have the option of not training the keys, have you also tried not training the values, namely the weights of EmbeddingBag?
Thanks in advance!

**Comment by glample** [comment]
Yes, we actually tried this by mistake, and it hurts the model quite a lot, unless the values are all initialized to 0 (but then this is like if you had no layer at all, which is of course worse than having a FFN layer). Overall, training the keys was always a bit better in our experiments (and training the values is critical).
