### ISSUE TITLE
A question about multi-GPU training

### ISSUE THREAD

**Issue by xiami2019** [facebookresearch/XLM#135]
Hi, guys.
I have a little question about your multi-GPU training. I wonder that the multi-GPU training aims to do model fusion or aims to split the mini-batch and put them into different GPUs.

**Comment by glample** [comment]
Hi,
It aims at using a different batch on each GPU, and synchronizing the gradients, which is equivalent to have a batch N times larger if you have N GPUs. We don't split the model, each process has its own copy of the model.

**Comment by xiami2019** [comment]
Thanks, I got it.(^_^)


 
---Original---
