### ISSUE TITLE
Attribute “StandardGpuResources” not in Faiss, when using HashingMemory

### ISSUE THREAD

**Issue by JianboTang** [facebookresearch/XLM#136]
When using HashingMemory as a layer in model, the attribute StandardGpuResources of Faiss is needed. However, the latest version of Faiss hasn't it. Hope, the version of Faiss available for HashingMemory is noticed.

**Comment by glample** [comment]
For the product keys, you don't need FAISS actually. It can be used at inference if you want to make the inference as fast as possible, but improvement is small compared to regular search.

**Comment by JianboTang** [comment]
Thank you very much for replying.  I just found some information warning that it would be significantly slower when FAISS is not available.

in file XLM/src/model/memory/utils.py#L162
sys.stderr.write("Switching to standard nearest neighbors search implementation, this will be significantly slower.\n")

**Comment by glample** [comment]
Mmm you are right. I copy pasted this message from another project were FAISS was really important, but here it's not critical at all (unless you want to use flat keys maybe). I updated the warning to make it sound less dramatic: https://github.com/facebookresearch/XLM/commit/46dd919b8ca1f22c11c4b121a6a8fd0d8fff7548

**Comment by JianboTang** [comment]
Thanks, again!
