### ISSUE TITLE
Parallel data used for TLM

### ISSUE THREAD

**Issue by fenfei** [facebookresearch/XLM#137]
In your get-data-para.sh script, we noticed that some of the datasets were commented out, such as all the OpenSubtitle datasets and the EU Bookshop dataset for en-es. We were wondering which datasets have you used in your paper for the TLM model?  Moreover, what batch_size (batch_size_per_gpu * num_gpu) were you using? How much does this number affect the results?

Thanks!

**Comment by aconneau** [comment]
Hi, the datasets we used for TLM model are mentioned in the paper (section 5.2). We've been using the largest batch_size that fits in 32Go of GPU memory. It depends on the model size, but when using large models, it's usually a batch size of 8, multiplied by 32 or 64 GPUs. We haven't made a comparison of the results wrt the batch_size but in our experience a large batch size is preferable.

**Comment by aconneau** [comment]
Closing the issue, feel free to re-open.
