### ISSUE TITLE
About "reset_positions" option

### ISSUE THREAD

**Issue by airkid** [facebookresearch/XLM#143]
Hi, I'm working on a problem which forms like XNLI dataset. In `xnli.py`, I found that `reset_positions` is always set to `False` when process batch data. In  this way XLM will consider the 2 sentence of each data example as 1 long sentence.  
Have you tried to set `reset_positions` to `True` ? If so, what the performance of these 2 setting?  
Thanks!

https://github.com/facebookresearch/XLM/blob/46dd919b8ca1f22c11c4b121a6a8fd0d8fff7548/src/evaluation/xnli.py#L128

**Comment by cocaer** [comment]
From my opinion
when training TLM,   reseting positions is reasonable because the 2 sentences comes from two language. But for xlni.py, it only has one language.
Reseting positions  "facilitate the alignment" during pretraining.

**Comment by aconneau** [comment]
As @cocaer mentioned, the logic of resetting positions for XNLI is that the model still sees one language, as compare to TLM where the sample is made of two parallel sentences. Similar in GLUE and in similar work, we don't reset positions but you could. I don't remember trying with reset_positions=true as there would have been a mismatch with pretraining where we don't reset positions for MLM.

**Comment by airkid** [comment]
Thanks for your replies!
