### ISSUE TITLE
./prepare-glue.sh only have MNLI not MNLI-m task

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/XLM#150]
As the name implied

**Comment by glample** [comment]
Why? MNLI-m and MNLI-mm are two different tasks.

**Comment by gaopengcuhk** [comment]
It seems the get_data_glue only download MNLI instead of MNLI-m and MNLI-mm

**Comment by aconneau** [comment]
225208007a85cd1d9c9dc3e4d375a3112fcbbe26 should fix it. Will update a script for downloading and preprocessing all GLUE tasks in the future.

**Comment by hpasapp** [comment]
note that 2252080 breaks prepare-glue.sh.
