### ISSUE TITLE
This code use dynamic masking or static masking?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/XLM#151]

**Comment by glample** [comment]
What is dynamic masking and static masking?

**Comment by gaopengcuhk** [comment]
In RoBERT and SpanBERT, dynamic masking is raised. In BERT, every-time the same position is masked. While in ROBERTA, dynamic mask position is generated each time.

**Comment by glample** [comment]
Here we sample randomly the masking position at each iteration, so I guess it's dynamic. Only exception is at evaluation time when we always use the same random generator to generate the masked positions. This way the masking is the same when evaluating at the end of epoch 1 and any other epoch (and the evaluation perplexities are comparable). But during training, it's totally random.

**Comment by gaopengcuhk** [comment]
Very timely response. Thank you very much for the good codebase and good explanation.
