### ISSUE TITLE
Question about the data

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/XLM#155]
Hello,

Thank you for making the code available!

I would like to ask a question regarding data pre-processing.

For pre-training a monolingual BERT model, you used the `WikiExtractor` script to obtain the texts from Wikipedia. This script, however, does not split the texts into individual sentences (i.e. each line of the output file can be a paragraph). Could you tell me how you dealt with this issue?

Thank you in advance for your response!

**Comment by aconneau** [comment]
Hi, our data loader turns input datasets into [text streams](https://github.com/facebookresearch/XLM/blob/master/src/data/dataset.py#L17) anyway so we didn't split the txt files at the sentence level.

**Comment by netw0rkf10w** [comment]
@aconneau Thanks a lot for your response!
