### ISSUE TITLE
Does the value of PKM stores in GPU memory or CPU memory?

### ISSUE THREAD

**Issue by ParadoxZW** [facebookresearch/XLM#158]
following code in memory.py makes me confused
``` Python
output = self.values(
            indices,
            per_sample_weights=scores.to(self.values.weight.data)
        ).to(scores) 
```
why use 'to' method?
The weights of value was stored in CPU memory(because value is too large to be held in GPU memory)?Or is it because value use different float with rest of the model(it seems that the whole model uses float16 as discribed in paper, but I failed to find any default set or converting to set float16 for PKM in code)

**Comment by glample** [comment]
It may be two things:
1) We indeed tried at some point to put the memory on CPU, but this was a bit slow. in that case this `to` conversion was necessary.
2) At some point, the `per_sample_weights` was not implemented for fp16 but only fp32 (in the last version of PyTorch it works with both). In that case we had to put the memory on float32 and have the rest of the model on fp16, which was not very convenient.

It's possible that now this conversion is totally useless. You can try to remove it and see if it still runs. If the scores are already on fp16 and the layer expects fp16, the `to` won't do anything anyway, so this conversion will not slow down the model if you can remove it.

**Comment by ParadoxZW** [comment]
thanks a lot
