### ISSUE TITLE
Comparison to Dynamic Convolutions

### ISSUE THREAD

**Issue by Phirefly9** [facebookresearch/XLM#161]
Good Morning,

In your paper you are using a new type of attention mechanism, however in neither the XLM paper or the "Large Memory Layers with Product Keys" paper did you discuss the strengths and weaknesses of the mechanism vs. another recent Facebook work "Pay Less Attention with Lightweight and Dynamic Convolutions" (or even cite)

Was there a performance reason to not use dynamic convolutions? Or what lead to generating a new mechanism over another potentially groundbreaking contribution?

**Comment by glample** [comment]
There is no relation between Product Keys Memories (PKM) and Lightweight Dynamic Convolutions (LDC). LDC is designed to fasten the self-attention process, and is very specific to Transformer models. PKM is designed to perform nearest neighbor search over a very large number of keys / values.  Although we give an instantiation of PKM to Transformers in the paper, it is a very generic approach that can be applied to any architecture, and for any domain.

In a Transformer, each layer is composed of a self-attention layer, and a feed-forward layer. PKM is used here to replace the feed-forward layer, and LDC is used to accelerate the self-attention. PKM and LDC are orthogonal components that both improve different parts of the transformer (and they could easily be used jointly).
