### ISSUE TITLE
pretrain on a corpus processed from the original information

### ISSUE THREAD

**Issue by songtaoshi** [facebookresearch/XLM#167]
Hi, how could I set parameters if I am pretraining in a corpus where the words are tokenized from the original chinese word? just the following.

> 4758 7647 16712 6299 11255 6068 695 23 19536 7142 7009 9655 10524 4864 7379 17348 7501 17225 14123 13711 7133 11255 21097 3277 6068 695 4190 1269 4526 12266 2161 17597 15274
23 6484 17225 8217 16374 11122 5592 21224 7251 11188 533 9685 11487 4246 19311 19851 8038 15822 9435 15274
1027 1269 14461 4815 12617 14123 3268 3390 8197 19019 16908 20958 15033 16541 19421 19429 7664 17253 4246 11123 1884 15274
5863 17166 21224 13159 2289 11944 8205 17083 13426 21224 17225 17186 14499 6225 16201 400 5635 3219 16498 15274

each separated line represents a paragraph

**Comment by songtaoshi** [comment]
@aconneau @glample

**Comment by aconneau** [comment]
I don't understand your query, could you elaborate? which parameters? how are the words "tokenized", you mean they are now numbers?

**Comment by songtaoshi** [comment]
Thanks for your reply! The words in my corpus are now numbers , which have been tokenized from Chinese word and I couldn’t get the words now , may just use the number to do the pretrianing, what parameters should I change when I use the train.py ?

**Comment by aconneau** [comment]
This should be exactly the same as [here](https://github.com/facebookresearch/XLM#1-preparing-the-data), except you don't apply the BPE part but you create the vocab (which in your case is gonna be a list of numbers), and then use the "python preprocess.py..." command. Then start your job as in the README.

**Comment by songtaoshi** [comment]
Thanks a lot!
