### ISSUE TITLE
How can I get the words embeddings?

### ISSUE THREAD

**Issue by stygian2a** [facebookresearch/XLM#17]
Hello!
Thank you for sharing this code!

Is there an easy way to get the embedding of a particular word?
Those found in table 5. of the paper.
Thank you!

**Comment by glample** [comment]
Hi!

Yes, I would suggest looking at the code in the notebook:
https://github.com/facebookresearch/XLM/blob/master/generate-embeddings.ipynb

Then doing something like that should work:
```python
word_id = dico.index('cat')
model.embeddings.weight[word_id]
```

**Comment by stygian2a** [comment]
Thank you! How can I differentiate words from different languages (ie 'chat' in french means cat)?

**Comment by glample** [comment]
You can just replace "cat" by "chat" in the code above. There is only one share vocabulary, that contains the words for all languages. The vocabulary doesn't keep track of which word is used in which language.

**Comment by stygian2a** [comment]
Got it, thx for everything!

**Comment by vtrokhymenko** [comment]
so, where i should take 'models/mlm_100_1280.pth'?
i want get models for russian language

**Comment by glample** [comment]
Yes, it contains Russian. But these two models will give you a better performance, and also support Russian:

https://dl.fbaipublicfiles.com/XLM/mlm_17_1280.pth
https://dl.fbaipublicfiles.com/XLM/mlm_100_1280.pth

**Comment by vtrokhymenko** [comment]
thx 

also, in this [notebook](https://github.com/facebookresearch/XLM/blob/master/generate-embeddings.ipynb) i get error at line `os.path.join(params.data_path, 'codes')`
> 'AttrDict' object has no attribute 'data_path'

u know how fix this?

**Comment by vtrokhymenko** [comment]
plus, for tokenization i should use this model for `mlm_17_1280.pth`?
![image](https://user-images.githubusercontent.com/8581044/63442646-20ddcf00-c43c-11e9-9c38-01b83d87396f.png)

**Comment by vtrokhymenko** [comment]
so, when i run `to_bpe(sentences)` i get next error 
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sentences.bpe'`

`tmp` folder i should create my hands? and where i should take `sentences.bpe`?

sorry, but your notebook have many errors at path to another users

**Comment by vtrokhymenko** [comment]
also, what does it mean?
`/private/home/aconneau/projects/XLM/data/wiki/17/175k/` i think this path are not available

**Comment by vtrokhymenko** [comment]
plus, at folder `tools` i didn't gave fastBPE
i should install from [here](github.com/glample/fastBPE) his ?

**Comment by vtrokhymenko** [comment]
solved errors and create new [pl](https://github.com/facebookresearch/XLM/pull/179) describing steps
