### ISSUE TITLE
Pretrained UMT models

### ISSUE THREAD

**Issue by maksym-del** [facebookresearch/XLM#170]
Hi, 

thanks for releasing the code and pre-trained BERT models!
Could you also release corresponding trained UMT models?

Thanks

**Comment by VigneshSrinivasan10** [comment]
It would be very useful to have pretrained UMT models!

**Comment by maksym-del** [comment]
@VigneshSrinivasan10 take a look at https://github.com/facebookresearch/XLM/issues/183
