### ISSUE TITLE
documentation: What are the 100 languages?

### ISSUE THREAD

**Issue by jowagner** [facebookresearch/XLM#173]
I cannot quickly find a list with the 100 languages that the 100 languages model is trained on. A link in the readme will help people with the same question.

Related: https://github.com/facebookresearch/XLM/issues/38

**Comment by thammegowda** [comment]
Haha I had the same feeling after scrolling the README 
Then, I managed to found this line in the middle of README:
> The XLM-100 model includes these languages: en-es-fr-de-zh-ru-pt-it-ar-ja-id-tr-nl-pl-simple-fa-vi-sv-ko-he-ro-no-hi-uk-cs-fi-hu-th-da-ca-el-bg-sr-ms-bn-hr-sl-zh_yue-az-sk-eo-ta-sh-lt-et-ml-la-bs-sq-arz-af-ka-mr-eu-tl-ang-gl-nn-ur-kk-be-hy-te-lv-mk-zh_classical-als-is-wuu-my-sco-mn-ceb-ast-cy-kn-br-an-gu-bar-uz-lb-ne-si-war-jv-ga-zh_min_nan-oc-ku-sw-nds-ckb-ia-yi-fy-scn-gan-tt-am

**Comment by thammegowda** [comment]
```
$ echo $x | tr '-' '\n' | sort  | awk '{print NR,$0}'
1 af
2 als
3 am
4 an
5 ang
6 ar
7 arz
8 ast
9 az
10 bar
11 be
12 bg
13 bn
14 br
15 bs
16 ca
17 ceb
18 ckb
19 cs
20 cy
21 da
22 de
23 el
24 en
25 eo
26 es
27 et
28 eu
29 fa
30 fi
31 fr
32 fy
33 ga
34 gan
35 gl
36 gu
37 he
38 hi
39 hr
40 hu
41 hy
42 ia
43 id
44 is
45 it
46 ja
47 jv
48 ka
49 kk
50 kn
51 ko
52 ku
53 la
54 lb
55 lt
56 lv
57 mk
58 ml
59 mn
60 mr
61 ms
62 my
63 nds
64 ne
65 nl
66 nn
67 no
68 oc
69 pl
70 pt
71 ro
72 ru
73 scn
74 sco
75 sh
76 si
77 simple
78 sk
79 sl
80 sq
81 sr
82 sv
83 sw
84 ta
85 te
86 th
87 tl
88 tr
89 tt
90 uk
91 ur
92 uz
93 vi
94 war
95 wuu
96 yi
97 zh
98 zh_classical
99 zh_min_nan
100 zh_yue
```
