### ISSUE TITLE
LM fine-tuning for non-english dataset (hindi)

### ISSUE THREAD

**Issue by nikhilno1** [facebookresearch/XLM#176]
Hi, pls see this thread for background: https://github.com/huggingface/pytorch-transformers/issues/1068

I want to build a text generator for hindi language that is fine-tuned on some dataset.
I understand that `xlm-clm-enfr-1024` and `xlm-clm-ende-1024` models are released for french and german languages. Is there any plan to release the same for other languages (specifically hindi)?
If not, could you pls share the steps so that we could do it ourselves?
Thank You.

**Comment by glample** [comment]
Hi,

Unfortunately no, we only trained CLM models with English, German and French.
To have a Hindi one, you will need to download Hindi monolingual data, you can check this corpus: http://www.cfilt.iitb.ac.in/iitb_parallel/ .
It is pretty good, and it has both parallel and monolingual data.

Then you can follow the steps of the repo to train a BERT model, and simply replace `--mlm_steps en` with  `--clm_steps hi` to train a causal model in Hindi.
