### ISSUE TITLE
How to save fine-tune models for XNLI task?

### ISSUE THREAD

**Issue by rajenchatterjee** [facebookresearch/XLM#18]
Hi,
I ran XNLI fine-tuning task (with MLM+TLM) and got an average accuracy of 73.5 (compared to 75.1 in your paper). The code generated params.pkl, however, I could not find the fine-tuned model. How do I save the model after fine-tuning (or after every epoch of fine-tuning)?

**Comment by rajenchatterjee** [comment]
Closing this issue. Sample code is available in train.py.

**Comment by MengZou0905** [comment]
I try to save the fine-tune models for XNLI as train.py does. However, I find that the saved model is just the same as the original mlm+tlm one. The updated parameters are not recorded. Could you share you solution? Thanks~

**Comment by MengZou0905** [comment]
> Closing this issue. Sample code is available in train.py.

I try to save the fine-tune models for XNLI as train.py does. However, I find that the saved model is just the same as the original mlm+tlm one. The updated parameters are not recorded. Could you share you solution? Thanks~

**Comment by adityapnusantara** [comment]
> Hi, I ran XNLI fine-tuning task (with MLM+TLM) and got an average accuracy of 73.5 (compared to 75.1 in your paper). The code generated params.pkl, however, I could not find the fine-tuned model. How do I save the model after fine-tuning (or after every epoch of fine-tuning)?

I have same problem.
