### ISSUE TITLE
Errors when reloading checkpoints

### ISSUE THREAD

**Issue by formiel** [facebookresearch/XLM#184]
I've got the 2 following errors when reloading 2 checkpoints to resume the 2 pretraining processes respectively. I've resumed the pretraining on the exact 2 servers that the checkpoints were trained previously.

The below error is what I got for the model of hidden size 512.
> Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 240, in main
    trainer = SingleTrainer(model, data, params)
  File "/home/bert/src/trainer.py", line 819, in __init__
    super().__init__(data, params)
  File "/home/bert/src/trainer.py", line 131, in __init__
    self.reload_checkpoint()
  File "/home/bert/src/trainer.py", line 547, in reload_checkpoint
    data = torch.load(checkpoint_path, map_location="cuda")
  File "/home/.env/python3/lib/python3.5/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/.env/python3/lib/python3.5/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 512

And the following error occurred to my model of hidden size 1024.
> Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 240, in main
    trainer = SingleTrainer(model, data, params)
  File "/home/bert/src/trainer.py", line 819, in __init__
    super().__init__(data, params)
  File "/home/bert/src/trainer.py", line 131, in __init__
    self.reload_checkpoint()
  File "/home/bert/src/trainer.py", line 546, in reload_checkpoint
    data = torch.load(checkpoint_path, map_location=lambda storage, loc: storage.cuda(self.params.local_rank))
  File "/home/.env/python3/lib/python3.5/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/.env/python3/lib/python3.5/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 8 more bytes. The file might be corrupted.

Regarding the latter error, I haven't done anything to the checkpoint file, so it's weird that it's corrupted in some way. I don't know if there is anyway to fix that.

Could you please help me on these two errors?  

Thank you very much in advance for your help!

**Comment by glample** [comment]
Maybe the experiment was killed while the model was saving the checkpoint. This is very surprising though. Can you try to run a new experiment, kill it after 1 epoch, and see if you can resume from the first epoch checkpoint, to see if the issue is reproducible?

**Comment by formiel** [comment]
Thank you so much for your quick response! I tried to run a new experiment and then kill it after 1 epoch but I couldn't manage to reproduce the issue. The code is able to reload the checkpoint now (I obtained a different error `RuntimeError: Error(s) in loading state_dict for TransformerModel` but it relates to the later step of reloading model parameters).

Below is the train log where the pretrained model was previously stopped (now I'm trying to reload the checkpoint from that). I should have included this earlier.

```
INFO - 08/21/19 20:48:41 - 11 days, 1:53:54 - ============ End of epoch 1338 ============
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - epoch -> 1338.000000
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - valid_fr_mlm_ppl -> 6.769886
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - valid_fr_mlm_acc -> 61.454065
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - valid_mlm_ppl -> 6.769886
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - valid_mlm_acc -> 61.454065
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - test_fr_mlm_ppl -> 6.568825
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - test_fr_mlm_acc -> 61.591214
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - test_mlm_ppl -> 6.568825
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - test_mlm_acc -> 61.591214
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - __log__:{"epoch": 1338, "valid_fr_mlm_ppl": 6.769886010381983, "valid_fr_mlm_acc": 61.45406537375945, "valid_mlm_ppl": 6.769886010381983, "valid_mlm_acc": 61.45406537375945, "test_fr_mlm_ppl": 6.568824553200027, "test_fr_mlm_acc": 61.59121449423104, "test_mlm_ppl": 6.568824553200027, "test_mlm_acc": 61.59121449423104}
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - Not a better validation score (8 / 20).
INFO - 08/21/19 20:49:16 - 11 days, 1:54:29 - Saving checkpoint to /home/bert/dumped/exp_name/checkpoint.pth ...
WARNING - 08/21/19 20:49:16 - 11 days, 1:54:29 - Saving {model} parameters ...
WARNING - 08/21/19 20:49:16 - 11 days, 1:54:29 - Saving {model} optimizer ...
INFO - 08/21/19 20:52:16 - 11 days, 1:57:28 - ============ Starting epoch 1339 ... ============
INFO - 08/21/19 20:52:23 - 11 days, 1:57:31 - 1673755 -    0.18 sent/s -     7.01 words/s - MLM-fr:  1.6976 -  - model LR: 3.0924e-05
INFO - 08/21/19 20:52:40 - 11 days, 1:57:38 - 1673760 -    5.60 sent/s -   209.59 words/s - MLM-fr:  1.7216 -  - model LR: 3.0924e-05
INFO - 08/21/19 20:52:43 - 11 days, 1:57:56 - 1673765 -    2.31 sent/s -    86.46 words/s - MLM-fr:  1.7943 -  - model LR: 3.0924e-05
INFO - 08/21/19 20:52:45 - 11 days, 1:57:58 - 1673770 -   15.67 sent/s -   605.04 words/s - MLM-fr:  1.7948 -  - model LR: 3.0924e-05
INFO - 08/21/19 20:52:48 - 11 days, 1:58:01 - 1673775 -   16.24 sent/s -   620.53 words/s - MLM-fr:  1.8036 -  - model LR: 3.0924e-05
...
...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 985, in emit
    self.flush()
  File "/usr/lib/python3.5/logging/__init__.py", line 965, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 290, in main
    trainer.iter()
  File "/home/bert/src/trainer.py", line 250, in iter
    self.print_stats()
  File "/home/
```
Thank you so much for your help!!

**Comment by glample** [comment]
I read this from your training log `OSError: [Errno 28] No space left on device` maybe it simply means that the model couldn't save the checkpoint because there was no space left on the device? Which would result in a corrupted checkpoint.

**Comment by formiel** [comment]
Yes, I think it makes sense. However, I'm still confused a little bit. At the end of epoch 1338, the checkpoint had already been saved. The disk space error occurred when the model was in the middle of training for epoch 1339. It hadn't reached the end of epoch 1339 yet. So I suppose the previously saved checkpoint at the end of epoch 1338 shouldn't be affected since the model hadn't started saving the current checkpoint for epoch 1339 yet. 

Anyway, I think maybe an option to avoid this issue is saving checkpoints periodically using the `save_periodic` option already provided in your code and change the parameter `include_optimizers` to `True` so that the periodic checkpoint would include optimiser's parameters. This would slow the code but maybe safer to avoid this kind of issue. 

Thank you so much again for your help!!

**Comment by formiel** [comment]
I just want to add another solution that I used, which is simply renaming the last checkpoint and save the current checkpoint. It would cost the disk space a little bit since there are always 2 checkpoints saved: the previous checkpoint and the current one.

```
# Rename last checkpoint
last_checkpoint = os.path.join(self.params.dump_path, 'checkpoint.pth')

if os.path.exists(last_checkpoint):
     renamed_checkpoint = os.path.join(self.params.dump_path, 'prev_checkpoint.pth')
     logger.info("Renaming previous checkpoint to {}".format(renamed_checkpoint))
     os.rename(last_checkpoint, renamed_checkpoint)
```
