### ISSUE TITLE
Training on multiple GPUs on multiple nodes

### ISSUE THREAD

**Issue by formiel** [facebookresearch/XLM#186]
Hello,

I am trying to train on a cluster with multiple nodes and would like to ask a question. 

In the `README` it is stated that:

> The multi-node is automatically handled by SLURM.

Does this mean that it is not necessary to use `srun` at all, and it suffices to use your recommended command like the following?
```
export NGPU=8
python -m torch.distributed.launch --nproc_per_node=$NGPU train.py
```
(In my case each node has 4 GPUs, so the above corresponds to 2 nodes.)

Thank you so much in advance for your help!

**Comment by glample** [comment]
Hi,

I would recommend having a look at this function: https://github.com/facebookresearch/XLM/blob/master/src/slurm.py#L46

This is the function that will parse the SLURM variables and detect whether the current experiment is part of a multi-GPU / multi-node experiment or not.

But you may have to adapt it to your cluster. We use SLURM internally, and I know that there are many ways to parametrize SLURM, so your environment variables may be different, and you may have to adapt the code to your cluster accordingly. I would imagine SLURM is pretty much the same anywhere and you don't have to change many things to make it work.

When I run a new experiment with SLURM, I use this file to run it with the `sbatch` command. Maybe you can try to start an experiment with something similar.

```bash
#!/bin/bash

{exclude}
{constraint}
{comment}
#SBATCH --time={time}
#SBATCH --mem={mem}g
#SBATCH --nodes={nodes}
#SBATCH --ntasks={ntasks}
#SBATCH --ntasks-per-node={ntasks_per_node}
#SBATCH --cpus-per-task={ncpu}
#SBATCH --gres=gpu:{ngpu}
#SBATCH --output={workdir}/%j.stdout
#SBATCH --error={workdir}/%j.stderr
#SBATCH --job-name={job_name}
#SBATCH --open-mode=append

cd {run_path}
LOG_STDOUT="{workdir}/$SLURM_JOB_ID.stdout"
LOG_STDERR="{workdir}/$SLURM_JOB_ID.stderr"

# Start (or restart) experiment
date >> $LOG_STDOUT
which python >> $LOG_STDOUT
echo "---Beginning program ---" >> $LOG_STDOUT
echo "Exp name     : {job_name}" >> $LOG_STDOUT
echo "SLURM Job ID : $SLURM_JOB_ID" >> $LOG_STDOUT
echo "SBATCH script: {filepath}" >> $LOG_STDOUT

srun --label {command} {exp_id} {master_port} &

wait $!
```

**Comment by formiel** [comment]
Thank you so much for your detailed response!! I understood now. My server has been under maintenance for some days so I haven't been able to test the SLURM job yet, but I think it will be fine.

**Comment by formiel** [comment]
I'm able to run the training on multiple GPUs and multiple nodes with SLURM now. Thank you so much!!!

**Comment by formiel** [comment]
Hello again!

First of all, congratulations on your NeurIPS spotlight acceptance! Awesome work!

My apology for re-opening this issue again as I am looking for a solution to a rather tricky issue with Slurm: the cluster that I'm using has a time limit of 20 hours per job, so it would require some 'resuming' mechanism for multiple-day training.

An idea I'm having in mind is to use a cron that regularly checks for the termination of the current job before submitting the next job that will resume the training. However, since Slurm is so popular, I think there should be a more standard solution, and I thought that maybe you or somebody here happen to have faced the same problem and could help me.

Thank you so much for your help!

**Comment by vsoto** [comment]
> I'm able to run the training on multiple GPUs and multiple nodes with SLURM now. Thank you so much!!!

Which command did you use with glimpse's script? python train.py or python -m torch.distributed.launch? Thanks for the help!

**Comment by formiel** [comment]
@vsoto I used the command `srun python train.py` with the parameter `master_port` being set to values between 10001 and 20000 to launch the training on server using Slurm to handle resources. https://github.com/facebookresearch/XLM/blob/ec48f7397bc5afb6c03e9a8e6a5a4e271682ed4b/src/slurm.py#L94

If your cluster does not use Slurm, then I think it's necessary to use `python -m torch.distributed.launch` with additional parameters related to number of nodes, master address etc. besides the parameter`--nproc_per_node=$NGPU`. You may refer to the following issue to run the script on multi nodes if your cluster does not use Slurm https://github.com/facebookresearch/XLM/issues/141.
