### ISSUE TITLE
can share me with three pretrained model for enro ende and enfr model based base model（hidden dim=512）

### ISSUE THREAD

**Issue by PlayDeep** [facebookresearch/XLM#188]
as the title, I still  pretraining all of the three model, but I have a deadline and can not wait it too long.if I have a pretrained model will speed up the pretraining. Help me with three pretrained model please.

**Comment by glample** [comment]
These three models are available here: https://github.com/facebookresearch/XLM#iii-applications-supervised--unsupervised-mt

**Comment by PlayDeep** [comment]
thank you for your sharing, however I need a pretrained model with hidden dim =512 .

**Comment by glample** [comment]
Unfortunately, we did not train a model with this dimension.

**Comment by PlayDeep** [comment]
I thought might be someone else will be train a model with this dimension, and you should not close my issue.
