### ISSUE TITLE
trainging model for languages with great differences

### ISSUE THREAD

**Issue by JiqiangLiu** [facebookresearch/XLM#19]
Thanks for you work. I have a question. When I training for languages with great differences, such as Chinese-English, English-Kazakh. Is it a good choice to share all parameters? I notice that XLM usually share all parameters.

**Comment by glample** [comment]
Hi, yes I don't think this is a problem. More and more studies have shown that a single model can handle multiple languages even when these are very different. Of course, if there are very few anchor points it is better to have parallel data to facilitate the alignment.

**Comment by JiqiangLiu** [comment]
Thanks for your instant reply. I will seriously in thinking about this question. The neural network is so amazing that some problems are difficult to understand. Such as share all the parameters for languages with few anchor points also still achieve good results.
