### ISSUE TITLE
Get sentence embeddings from a pretrained model

### ISSUE THREAD

**Issue by duyvuleo** [facebookresearch/XLM#193]
Hi,

Thanks for great work. 

I used XLM to train a BERT-only model for Vietnamese language using monolingual wiki data. 

I used the following command for training the BERT model:

```
export PYTHONPATH=$PYTHONPATH:/oradiskvdb/vuh/projects/VieBERT/code/XLM/
export NGPU=2; python -m torch.distributed.launch --nproc_per_node=$NGPU  /oradiskvdb/vuh/projects/VieBERT/code/XLM/train.py --exp_name model-base-xlm-vi-wiki --dump_path /oradiskvdb/vuh/projects/VieBERT/exp/XLM/ --data_path /oradiskvdb/vuh/projects/VieBERT/data/vi-wiki-dumps/pth-bpe30k  --lgs 'vi' --clm_steps '' --mlm_steps 'vi' --emb_dim 512 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true  --batch_size 64 --bptt 256 --max_len 128 --optimizer adam_inverse_sqrt,lr=0.00010,warmup_updates=30000,beta1=0.9,beta2=0.999,weight_decay=0.01,eps=0.000001 --epoch_size 100000 --max_epoch 100000 --validation_metrics _valid_vi_mlm_ppl  --stopping_criterion _valid_vi_mlm_ppl,25  --word_mask_keep_rand '0.8,0.1,0.1' --word_pred '0.15' --sinusoidal_embeddings true
```

Then after training for a week (ppl on test around 4), I wrote a bit of code to generate sentence embeddings, e.g., 

```
python /oradiskvdb/vuh/projects/VieBERT/code/XLM/generate-embeddings.py --data_path /oradiskvdb/vuh/projects/VieBERT/data/vi-wiki-dumps/pth-bpe30k --model_path /oradiskvdb/vuh/projects/VieBERT/exp/XLM/model-base-xlm-vi-wiki/e8mq827v4a/best-valid_vi_mlm_ppl.pth
```

The content of generate-embeddings.py is attached in the following file:

[generate-embeddings.txt](https://github.com/facebookresearch/XLM/files/3593177/generate-embeddings.txt)

BUT I always got the following errors:

> Traceback (most recent call last):
>   File "/oradiskvdb/vuh/projects/VieBERT/code/XLM/generate-embeddings.py", line 38, in <module>
>     embedder = SentenceEmbedder.reload(params.model_path, params)
>   File "/oradiskvdb/vuh/projects/VieBERT/code/XLM/src/model/embedder.py", line 46, in reload
>     model.load_state_dict(state_dict)
>   File "/oradiskvdb/vuh/tools/pyvenv3-gpu-torch/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for TransformerModel:
> 	Missing key(s) in state_dict: "position_embeddings.weight", "embeddings.weight", "layer_norm_emb.weight", "layer_norm_emb.bias", "attentions.0.q_lin.weight", "attentions.0.q_lin.bias", "attentions.0.k_lin.weight", "attentions.0.k_lin.bias", "attentions.0.v_lin.weight", "attentions.0.v_lin.bias", "attentions.0.out_lin.weight", "attentions.0.out_lin.bias", "attentions.1.q_lin.weight", "attentions.1.q_lin.bias", "attentions.1.k_lin.weight", "attentions.1.k_lin.bias", "attentions.1.v_lin.weight", "attentions.1.v_lin.bias", "attentions.1.out_lin.weight", "attentions.1.out_lin.bias", "attentions.2.q_lin.weight", "attentions.2.q_lin.bias", "attentions.2.k_lin.weight", "attentions.2.k_lin.bias", "attentions.2.v_lin.weight", "attentions.2.v_lin.bias", "attentions.2.out_lin.weight", "attentions.2.out_lin.bias", "attentions.3.q_lin.weight", "attentions.3.q_lin.bias", "attentions.3.k_lin.weight", "attentions.3.k_lin.bias", "attentions.3.v_lin.weight", "attentions.3.v_lin.bias", "attentions.3.out_lin.weight", "attentions.3.out_lin.bias", "attentions.4.q_lin.weight", "attentions.4.q_lin.bias", "attentions.4.k_lin.weight", "attentions.4.k_lin.bias", "attentions.4.v_lin.weight", "attentions.4.v_lin.bias", "attentions.4.out_lin.weight", "attentions.4.out_lin.bias", "attentions.5.q_lin.weight", "attentions.5.q_lin.bias", "attentions.5.k_lin.weight", "attentions.5.k_lin.bias", "attentions.5.v_lin.weight", "attentions.5.v_lin.bias", "attentions.5.out_lin.weight", "attentions.5.out_lin.bias", "layer_norm1.0.weight", "layer_norm1.0.bias", "layer_norm1.1.weight", "layer_norm1.1.bias", "layer_norm1.2.weight", "layer_norm1.2.bias", "layer_norm1.3.weight", "layer_norm1.3.bias", "layer_norm1.4.weight", "layer_norm1.4.bias", "layer_norm1.5.weight", "layer_norm1.5.bias", "ffns.0.lin1.weight", "ffns.0.lin1.bias", "ffns.0.lin2.weight", "ffns.0.lin2.bias", "ffns.1.lin1.weight", "ffns.1.lin1.bias", "ffns.1.lin2.weight", "ffns.1.lin2.bias", "ffns.2.lin1.weight", "ffns.2.lin1.bias", "ffns.2.lin2.weight", "ffns.2.lin2.bias", "ffns.3.lin1.weight", "ffns.3.lin1.bias", "ffns.3.lin2.weight", "ffns.3.lin2.bias", "ffns.4.lin1.weight", "ffns.4.lin1.bias", "ffns.4.lin2.weight", "ffns.4.lin2.bias", "ffns.5.lin1.weight", "ffns.5.lin1.bias", "ffns.5.lin2.weight", "ffns.5.lin2.bias", "layer_norm2.0.weight", "layer_norm2.0.bias", "layer_norm2.1.weight", "layer_norm2.1.bias", "layer_norm2.2.weight", "layer_norm2.2.bias", "layer_norm2.3.weight", "layer_norm2.3.bias", "layer_norm2.4.weight", "layer_norm2.4.bias", "layer_norm2.5.weight", "layer_norm2.5.bias", "pred_layer.proj.weight", "pred_layer.proj.bias".
> 	Unexpected key(s) in state_dict: "module.position_embeddings.weight", "module.embeddings.weight", "module.layer_norm_emb.weight", "module.layer_norm_emb.bias", "module.attentions.0.q_lin.weight", "module.attentions.0.q_lin.bias", "module.attentions.0.k_lin.weight", "module.attentions.0.k_lin.bias", "module.attentions.0.v_lin.weight", "module.attentions.0.v_lin.bias", "module.attentions.0.out_lin.weight", "module.attentions.0.out_lin.bias", "module.attentions.1.q_lin.weight", "module.attentions.1.q_lin.bias", "module.attentions.1.k_lin.weight", "module.attentions.1.k_lin.bias", "module.attentions.1.v_lin.weight", "module.attentions.1.v_lin.bias", "module.attentions.1.out_lin.weight", "module.attentions.1.out_lin.bias", "module.attentions.2.q_lin.weight", "module.attentions.2.q_lin.bias", "module.attentions.2.k_lin.weight", "module.attentions.2.k_lin.bias", "module.attentions.2.v_lin.weight", "module.attentions.2.v_lin.bias", "module.attentions.2.out_lin.weight", "module.attentions.2.out_lin.bias", "module.attentions.3.q_lin.weight", "module.attentions.3.q_lin.bias", "module.attentions.3.k_lin.weight", "module.attentions.3.k_lin.bias", "module.attentions.3.v_lin.weight", "module.attentions.3.v_lin.bias", "module.attentions.3.out_lin.weight", "module.attentions.3.out_lin.bias", "module.attentions.4.q_lin.weight", "module.attentions.4.q_lin.bias", "module.attentions.4.k_lin.weight", "module.attentions.4.k_lin.bias", "module.attentions.4.v_lin.weight", "module.attentions.4.v_lin.bias", "module.attentions.4.out_lin.weight", "module.attentions.4.out_lin.bias", "module.attentions.5.q_lin.weight", "module.attentions.5.q_lin.bias", "module.attentions.5.k_lin.weight", "module.attentions.5.k_lin.bias", "module.attentions.5.v_lin.weight", "module.attentions.5.v_lin.bias", "module.attentions.5.out_lin.weight", "module.attentions.5.out_lin.bias", "module.layer_norm1.0.weight", "module.layer_norm1.0.bias", "module.layer_norm1.1.weight", "module.layer_norm1.1.bias", "module.layer_norm1.2.weight", "module.layer_norm1.2.bias", "module.layer_norm1.3.weight", "module.layer_norm1.3.bias", "module.layer_norm1.4.weight", "module.layer_norm1.4.bias", "module.layer_norm1.5.weight", "module.layer_norm1.5.bias", "module.ffns.0.lin1.weight", "module.ffns.0.lin1.bias", "module.ffns.0.lin2.weight", "module.ffns.0.lin2.bias", "module.ffns.1.lin1.weight", "module.ffns.1.lin1.bias", "module.ffns.1.lin2.weight", "module.ffns.1.lin2.bias", "module.ffns.2.lin1.weight", "module.ffns.2.lin1.bias", "module.ffns.2.lin2.weight", "module.ffns.2.lin2.bias", "module.ffns.3.lin1.weight", "module.ffns.3.lin1.bias", "module.ffns.3.lin2.weight", "module.ffns.3.lin2.bias", "module.ffns.4.lin1.weight", "module.ffns.4.lin1.bias", "module.ffns.4.lin2.weight", "module.ffns.4.lin2.bias", "module.ffns.5.lin1.weight", "module.ffns.5.lin1.bias", "module.ffns.5.lin2.weight", "module.ffns.5.lin2.bias", "module.layer_norm2.0.weight", "module.layer_norm2.0.bias", "module.layer_norm2.1.weight", "module.layer_norm2.1.bias", "module.layer_norm2.2.weight", "module.layer_norm2.2.bias", "module.layer_norm2.3.weight", "module.layer_norm2.3.bias", "module.layer_norm2.4.weight", "module.layer_norm2.4.bias", "module.layer_norm2.5.weight", "module.layer_norm2.5.bias", "module.pred_layer.proj.weight", "module.pred_layer.proj.bias".

Would you please advise what is wrong with my code/command? Thank you very much!

**Comment by glample** [comment]
Hi,

I think this is because the file you are trying to reload is a checkpoint file, in which the model is encapsulated into a module that takes care of distributed training.

Can you try something like this before reloading?
```python
if all(k.startswith('module.') for k in state_dict.keys()):
    state_dict = {k[len('module.'):]: v for k, v in state_dict.items()}
assert not any(k.startswith('module.') for k in state_dict.keys())
```

**Comment by duyvuleo** [comment]
Thanks for your response. 

In fact, I found the code inside SentenceEmbedder already did that, i.e., [lines](https://github.com/facebookresearch/XLM/blob/e6ecf4679194cf28ece8ad8c9035de6140470ff0/src/model/embedder.py#L31). But the checkpoint file must contain "checkpoint" to make it work properly.
