### ISSUE TITLE
Wrong data_path in the generate-embeddings notebook

### ISSUE THREAD

**Issue by james-assiene** [facebookresearch/XLM#196]
Hi,

In the first cell in the section "Get sentence representations", the line below provokes an error
`codes = os.path.join(params.data_path, 'codes')`

Besides the fact that "mlm_tlm ..." and "mlm_xnli ..." pre-trained models params don't have a "data_path" key, the value of params.data_path for "mlm_en_2048.pth" is "/private/home/aconneau/projects/XLM/data/wiki/en/30k"

To fix this issue I had to replace the "params.data_path" by "data/processed/XLM_en/30k" since it's where the processed codes are located. After that everything went fine

I just want to suggest to make this modification so that other users won't encounter the same problem

Thanks!

**Comment by aconneau** [comment]
Thanks for pointing it out. The code path needs indeed to be set manually depending on the model you're using.
