### ISSUE TITLE
NaN during training

### ISSUE THREAD

**Issue by ebilal** [facebookresearch/XLM#210]
Running
export NGPU=2; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py \
--exp_name xlm_en \
--dump_path ./dumped \
--data_path data/processed/XLM_en/30k \
--lgs 'en' \
--clm_steps '' \
--mlm_steps 'en' \
--emb_dim 768 \
--n_layers 12 \
--n_heads 12 \
--dropout 0.1 \
--attention_dropout 0.1 \
--gelu_activation true \
--batch_size 32 \
--bptt 256 \
--optimizer adam_inverse_sqrt,lr=0.00010,warmup_updates=30000,beta1=0.9,beta2=0.999,weight_decay=0.01,eps=0.000001 \
--epoch_size 300000 \
--max_epoch 100000 \
--validation_metrics _valid_en_mlm_ppl \
--stopping_criterion _valid_en_mlm_ppl,25 \
--fp16 true \
--amp 3 \
--word_mask_keep_rand '0.8,0.1,0.1' \
--word_pred '0.15'

gives out NaN values after not too many iterations

INFO - 10/04/19 16:19:13 - 0:19:05 -    4145 -  118.14 sent/s -  4536.51 words/s - MLM-en:  8.1367 -  - model LR: 1.3903e-05
INFO - 10/04/19 16:19:13 - 0:19:05 -    4145 -  118.12 sent/s -  4447.37 words/s - MLM-en:  8.1219 -  - model LR: 1.3903e-05
WARNING - 10/04/19 16:19:13 - 0:19:06 - NaN detected
WARNING - 10/04/19 16:19:13 - 0:19:06 - NaN detected
WARNING - 10/04/19 16:19:14 - 0:19:06 - NaN detected
WARNING - 10/04/19 16:19:14 - 0:19:06 - NaN detected
WARNING - 10/04/19 16:19:14 - 0:19:06 - NaN detected
WARNING - 10/04/19 16:19:14 - 0:19:06 - NaN detected
INFO - 10/04/19 16:19:14 - 0:19:07 -    4150 -  118.05 sent/s -  4568.65 words/s - MLM-en:     nan -  - model LR: 1.3919e-05
INFO - 10/04/19 16:19:14 - 0:19:07 -    4150 -  118.07 sent/s -  4504.41 words/s - MLM-en:     nan -  - model LR: 1.3919e-05

**Comment by glample** [comment]
`--amp 3` is usually very unstable, in practice we never use it. We always set `--amp 2` for float16.
