### ISSUE TITLE
weird codes in Evaluator.get_iterator

### ISSUE THREAD

**Issue by yilinyang7** [facebookresearch/XLM#22]
Hi,

I just found out a weird piece at: https://github.com/facebookresearch/XLM/blob/20c338e68bc90595720d9f25d37204fc86fc5b12/src/evaluation/evaluator.py#L52-L56

If possible, may I ask the intuition behind this "hack".

Thanks.

**Comment by glample** [comment]
If you train a model on 100 languages, you probably don't want to evaluate how well it performs on all of them during training, as computing the average perplexity of all languages at the end of an epoch will take forever. The idea is to do that during training, then evaluate without the hack once the model is trained.

**Comment by yilinyang7** [comment]
> If you train a model on 100 languages, you probably don't want to evaluate how well it performs on all of them during training, as computing the average perplexity of all languages at the end of an epoch will take forever. The idea is to do that during training, then evaluate without the hack once the model is trained.

Thanks for the explanation. Then I guess the first assignment of eval_lgs is removable.

**Comment by glample** [comment]
Yes. And this entire code is removable if you are not planning to use more than 30 languages.
