### ISSUE TITLE
Which `faiss` version is required to run the code with product key memory

### ISSUE THREAD

**Issue by rrkarim** [facebookresearch/XLM#228]
I'm installing `faiss` following the official instructions, meaning now I've got `1.6` and the code throws the error with `TypeError: bruteForceKnn() takes exactly 12 arguments (10 given)`. I haven't seen any changes in release notes concerning the change of `bruteForceKnn()` logic.

**Comment by rrkarim** [comment]
So yeah, `HashingMemoryProductFast(...)._get_indices` method works alright, but there are some problems with the parent class. I guess It was already raised before.

**Comment by glample** [comment]
Hi,

It's possible that the API of FAISS changed recently. I'll look into it. In the meantime, you can simply disable FAISS. With product keys, using FAISS or PyTorch for nearest neighbor search does not make a big difference (actually, no difference at all during training, since we don't use FAISS at training time, and barely any difference at inference time).

**Comment by rrkarim** [comment]
Hi, there is just an ambiguity with the namings of memory classes. `HashingMemoryProduct` uses `faiss` by default, `HashingMemoryProductFast` does not.

**Comment by glample** [comment]
Yes, code may be a bit confusing as there are a few classes doing the same thing, just with different implementations. Sorry about that. You should only use `HashingMemoryProductFast`. `HashingMemoryProduct` is something we implemented first, which was not as fast, but that I did not remove from the code. The only thing you need is basically what there is in https://github.com/facebookresearch/XLM/blob/master/PKM-layer.ipynb which is `HashingMemoryProductFast`.

**Comment by glample** [comment]
`topk` is not faster, FAISS is faster if you have to search the nearest neighbor within 1 000 000 elements, but with the product key, you only need to search in about 1 000 keys, and in that setting `topk` is basically just as fast, and does not have the FAISS overhead.

**Comment by rrkarim** [comment]
Ok, I see that, thanks. I guess you can close the issue if there is nothing to fix for now.
