### ISSUE TITLE
How can I use multi-GPU to train UNMT

### ISSUE THREAD

**Issue by hpsun1109** [facebookresearch/XLM#23]
I add --local_rank, but raise error.

SLURM job: False
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    main(params)
  File "train.py", line 198, in main
    init_distributed_mode(params)
  File "XLM/src/slurm.py", line 110, in init_distributed_mode
    params.global_rank = int(os.environ['RANK'])
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by hpsun1109** [comment]
another question, in the UNMT model, only one encoder and one decoder? Thanks.

**Comment by glample** [comment]
You should not handle the `--local_rank` yourself. You can use the following command to train with multi-GPU: https://github.com/facebookresearch/XLM#how-can-i-run-experiments-on-multiple-gpus

```
export NGPU=8; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py ARGUMENTS
```

And no, there are 2 separate models for UNMT, one encoder and one decoder, but they are initialized with the same weights (apart from the parameters of the source attention in the decoder that remain randomly initialized).

**Comment by BinWone** [comment]
> You should not handle the `--local_rank` yourself. You can use the following command to train with multi-GPU: https://github.com/facebookresearch/XLM#how-can-i-run-experiments-on-multiple-gpus
> 
> ```
> export NGPU=8; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py ARGUMENTS
> ```
> 
> And no, there are 2 separate models for UNMT, one encoder and one decoder, but they are initialized with the same weights (apart from the parameters of the source attention in the decoder that remain randomly initialized).

I using multi-GPU to pre-training the model like `export NGPU=8; python -m torch.distributed.launch --nproc_per_node=$NGPU train.py ARGUMENTS`, it just run the same job on 8 GPUs, the training time is the same as training on 1 GPU, it doesn't fast the pre-training process.
How to set the params and I can fast the training process on multi-GPU?

**Comment by glample** [comment]
What do you mean by the training time is the same? Is the perplexity the same at the end of a few epochs? Or do you look at the number of words per second? The number of words per second in the log is given per GPU, so this will be the same. But the loss / perplexity should decrease much faster.

**Comment by BinWone** [comment]
> What do you mean by the training time is the same? Is the perplexity the same at the end of a few epochs? Or do you look at the number of words per second? The number of words per second in the log is given per GPU, so this will be the same. But the loss / perplexity should decrease much faster.

yes, i made a mistake. you are right, multi-gpu training get better valid ppl and acc.
pretraining on 1 GPU:
![image](https://user-images.githubusercontent.com/11994164/60661931-aa860d00-9e8d-11e9-9510-0826ad2b7982.png)
on 4 GPU
![image](https://user-images.githubusercontent.com/11994164/60661987-bd98dd00-9e8d-11e9-81bd-126a58f6248e.png)

**Comment by glample** [comment]
Looks good :)
