### ISSUE TITLE
reloading decoder from mlm_1024.pth

### ISSUE THREAD

**Issue by JiqiangLiu** [facebookresearch/XLM#24]
Hi, thanks for your work. When I reloading decoder from mlm_1024.pth that has been pretrained, the warnings are rised as follow:
```
WARNING - 03/03/19 10:07:57 - 0:00:37 - Parameter layer_norm15.0.weight not found.
WARNING - 03/03/19 10:07:57 - 0:00:37 - Parameter layer_norm15.0.bias not found.
WARNING - 03/03/19 10:07:57 - 0:00:37 - Parameter encoder_attn.0.q_lin.weight not found.
WARNING - 03/03/19 10:07:57 - 0:00:37 - Parameter encoder_attn.0.q_lin.bias not found.
WARNING - 03/03/19 10:07:57 - 0:00:37 - Parameter encoder_attn.0.k_lin.weight not found.
...
```
https://github.com/facebookresearch/XLM/blob/ffc64a9e4ce21a601f2803c544c916a54e55a0e2/src/model/__init__.py#L151
My training is for unsupervised NMT. Is is the normal? How to fix it? Thank you very much.

**Comment by glample** [comment]
Yes this is normal. When you pretrain the decoder, you use a model trained with the MLM objective, and this model does not do source attention, as this is very specific to MT. As a result, these parameters cannot be pretrained. The WARNING will show you the parameters that were not reloaded, and these ones should be exactly the ones not in the encoder. The code would crash at this line if there were something wrong: https://github.com/facebookresearch/XLM/blob/ffc64a9e4ce21a601f2803c544c916a54e55a0e2/src/model/__init__.py#L162

**Comment by JiqiangLiu** [comment]
I get it. Thanks.
