### ISSUE TITLE
Decoder pretraining with MLM - how?

### ISSUE THREAD

**Issue by rubencart** [facebookresearch/XLM#240]
Hi, I enjoyed reading your paper 🙂. I have a question however.
Table 2 lists different ways of pretraining the encoder and decoder for unsupervised machine translation, and it says that you tried training your decoder with MLM. In the BERT paper, Devlin et al. only use a transformer **encoder** however.
Looking at your code, in src/trainer.py your `EncDecTrainer` class uses the `mlm_step(...)` method from its `Trainer` superclass. This method (line 706) only trains the **encoder**. 
So, my actual question: how then do you pretrain the **decoder** with MLM? Do you pretrain it as if it were an encoder, and then just initialize the decoder with these params? Or am I overlooking something?

**Comment by Jeevesh8** [comment]
I have the same question. Please help , if you find any answer.

**Comment by rubencart** [comment]
@Jeevesh8 I ended up sending Guillaume Lample (author) an email with the question. This is what he replied (I hope he's okay with me sharing it here).
"Yes, what we do to pretrain the decoder is actually very simple. We just initialize it with the same weights as the encoder. The only issue is that the decoder has some extra parameters that the encoder do not have, that are the source attention parameters. So what we do is that we pretrain all parameters, and leave the source attention parameters randomly initialized. It is not optimal, but it works better than not pretraining the decoder at all."

**Comment by Jeevesh8** [comment]
Thank you very much @rubencart  , for telling. :)
