### ISSUE TITLE
Can I run the MLM and BT objectives together?

### ISSUE THREAD

**Issue by Akella17** [facebookresearch/XLM#241]
I need to perform an experiment that involves both MLM and BT (back-translation) tasks over multiple languages. However, I am facing this error when I try running the code on 2 GPUs. **Note**: *This only happens when running the multi-GPU code. Single GPU code runs fine.*

```RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:408)```

This problem persists even after setting the ```find_unused_parameters=True``` in the ```torch.nn.parallel.DistributedDataParallel```.

**Comment by zwhe99** [comment]
same issue here. Have you solved this problem?
