### ISSUE TITLE
The output dimension of the actual model is not consistent with the corresponding vocab

### ISSUE THREAD

**Issue by 645709712** [facebookresearch/XLM#256]
I use the pretrained model of 100 languages model and corresponding vocab.
But when I load the model, I find that the output dimension of the actual model is not consistent with the corresponding vocab.The error message is as follows:
        size mismatch for pred_layer.proj.weight: copying a param with shape torch.Size([200000, 1280]) from checkpoint, the shape in current model is torch.Size([239769, 1280]). 

You can see that the output dimension in the actual model is 200000,the vocab size is 239769.
So what I want to ask is what special treatment does the model do for the size of vocab? Why are there inconsistent dimensions?

**Comment by glample** [comment]
Yes, you have to use `--max_vocab 200000` in that setting.
