### ISSUE TITLE
 logger.error(f"{p} not found

### ISSUE THREAD

**Issue by masonreznov** [facebookresearch/XLM#262]
Hello @aconneau @glample @Celebio 

I came into an error after running the following command.

`python train.py --exp_name unsupMT_enfr --dump_path ./dumped/ --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path ./data/processed/en-fr/ --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 2000 --batch_size 32 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu' 
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from src.data.loader import check_data_params, load_data
  File "/home/michael/TRANSLATION/XLM/src/data/loader.py", line 296
    logger.error(f"{p} not found")
                                ^
SyntaxError: invalid syntax
`

Any help is appreciated

Michael

**Comment by lihongzheng-nlp** [comment]
Hello @masonreznov  I also met the exact same problem as you met when I pre-trained the LM,
 `line 296 logger.error(f"{p} not found") ^ SyntaxError: invalid syntax` 
have you ever solved it? Thank you! @aconneau @glample

**Comment by glample** [comment]
Are you using Python2 or Python3? This line looks fine, but would not run with Python 2.

**Comment by lihongzheng-nlp** [comment]
@glample Thanks for your comments. I use python 3.5.2.

**Comment by glample** [comment]
I see. It looks like f-strings are only available since Python 3.6
You can probably replace this line by: `logger.error("%s not found" % p)`
but I suspect there are many locations in the code that use f-string so it will probably break somewhere else. I guess the simplest is to use a more recent version of Python.
