### ISSUE TITLE
Unsupervised MT without any parallel data for valid/test?

### ISSUE THREAD

**Issue by ramimanna** [facebookresearch/XLM#264]
Hi,

I'm trying to run unsupervised MT. I'm able to pre-train successfully, but when I try to train, I'm getting an assertion error.
Here's the command I'm running:
```bash
export NGPU=4; 
export RANK=$NGPU;
export WORLD_SIZE=$NGPU;
python -m torch.distributed.launch --nproc_per_node=$NGPU \
train.py --exp_name train_asar --dump_path ./dumped/ \
			    --reload_model './dumped/test_asar_mlm/378251/checkpoint.pth,./dumped/test_asar_mlm/378251/checkpoint.pth' \
			     --data_path ./data/processed/as-ar/ --lgs 'as-ar' --ae_steps 'as,ar' --bt_steps 'as-ar-as,ar-as-ar' \
			     --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' \
			     --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 \
			     --gelu_activation true --tokens_per_batch 2000 --batch_size 32 --bptt 256 \
			     --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --max_epoch=1 --eval_bleu true \
			     --fp16 true --amp 1

```

The assertion error that I get is this one:
https://github.com/facebookresearch/XLM/blob/9e6f6814d17be4fe5b15f2e6c43eb2b2d76daeb4/src/data/loader.py#L317

I'm getting this error because I don't have the files:
```
./data/processed/as-ar/valid.ar-as.ar.pth not found
./data/processed/as-ar/valid.ar-as.as.pth not found
./data/processed/as-ar/test.ar-as.ar.pth not found
./data/processed/as-ar/test.ar-as.as.pth not found
```

It seems like my param: `--bt_steps 'as-ar-as,ar-as-ar'` parameter is causing this by adding to the `required_para` set:
https://github.com/facebookresearch/XLM/blob/9e6f6814d17be4fe5b15f2e6c43eb2b2d76daeb4/src/data/loader.py#L301
I'm a bit confused about why `bt_steps` would require any parallel data. Doesn't back translation only require monolingual data?  I don't have any parallel data at all (neither for train nor for valid/test). My guess is that parallel valid/test data is only being required so that evaluation metrics can be used after training. Is this the case?

Is there any way I can train without any parallel data at all (not even for valid or test)?

**Comment by VigneshSrinivasan10** [comment]
@ramimanna I am having this same problem, how did you resolve it ? 
Any tips would be greatly appreciated!

**Comment by fallcat** [comment]
You can make empty or random files for those.
