### ISSUE TITLE
How to get train/evaluation data about GLUE task

### ISSUE THREAD

**Issue by YaaoTu** [facebookresearch/XLM#27]
Hi 

Thank you for the great contribution
Is there any script to download data of GLUE tasks?

**Comment by glample** [comment]
Hi

Sorry for the delay. We will upload it by tomorrow.

**Comment by YaaoTu** [comment]
Thanks a lot!

**Comment by aconneau** [comment]
I uploaded a [script for downloading and preprocessing](https://github.com/facebookresearch/XLM/blob/master/get-data-glue.sh 5 GLUE tasks): SST-2, STS-B, MNLI, QNLI and QQP.
I tested it on my config and it worked fine. This would be very helpful if you can let me know if that works on your side.

Thanks!
Alexis
