### ISSUE TITLE
gzip: invalid option -- 'k'

### ISSUE THREAD

**Issue by iConBarca** [facebookresearch/XLM#271]
When I want to preprocess the data, there is something wrong.
./get-data-nmt.sh --src en --tgt fr --reload_codes codes_enfr --reload_vocab vocab_enfr
And there is nothing in ./data/processed/en-fr/.

**Comment by smart-patrol** [comment]
@iConBarca  How did you fix this? I am getting the same error.

**Comment by iConBarca** [comment]
just remove -k in source code.

**Comment by iConBarca** [comment]
@smart-patrol Just remove the '-k' in get-data-nmt.sh

**Comment by smart-patrol** [comment]
Thanks. Removing it worked. Guess --keep is now implied.
