### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for TransformerModel

### ISSUE THREAD

**Issue by shaunlim0105** [facebookresearch/XLM#280]
Hi,
I'm trying to fine-tune the pretrained model( by reloading the **mlm_17_1280**) on a custom dataset for MLM+TLM tasks. I've processed and binarized my dataset using the existing BPE codes and vocabs for mlm_17_1280. 

_By running the following:_
CUDA_VISIBLE_DEVICES=2 python /home/slim72/XLM/train.py \
--exp_name=xlm_en_ko --dump_path=/home/slim72/XLM-model --data_path=/home/slim72/XLM-data --lgs=en-ko \
--mlm_steps=en-ko --emb_dim=1280 --n_layers=12 --n_heads=16 --dropout=0.1 --attention_dropout=0.1 --gelu_activation=true \
--batch_size=32 --bptt=256 --optimizer=adam,lr=0.0001 --epoch_size=300000 --max_epoch=100000 --validation_metrics=_valid_mlm_ppl \
--stopping_criterion=_valid_mlm_ppl,25 --fp16=true --reload_model=/home/slim72/XLM/mlm_17_1280.pth --max_vocab=200000

_I get the following error:_
Missing key(s) in state_dict: "lang_embeddings.weight". 
        Unexpected key(s) in state_dict: "attentions.12.q_lin.weight", "attentions.12.q_lin.bias", "attentions.12.k_lin.weight", "attentions.12.k_lin.bias", "attentions.12.v_lin.weight", "attentions.12.v_lin.bias", "attentions.12.out_lin.weight", "attentions.12.out_lin.bias", "attentions.13.q_lin.weight", "attentions.13.q_lin.bias", "attentions.13.k_lin.weight", "attentions.13.k_lin.bias", "attentions.13.v_lin.weight", "attentions.13.v_lin.bias", "attentions.13.out_lin.weight", "attentions.13.out_lin.bias", "attentions.14.q_lin.weight", "attentions.14.q_lin.bias", "attentions.14.k_lin.weight", "attentions.14.k_lin.bias", "attentions.14.v_lin.weight", "attentions.14.v_lin.bias", "attentions.14.out_lin.weight", "attentions.14.out_lin.bias", "attentions.15.q_lin.weight", "attentions.15.q_lin.bias", "attentions.15.k_lin.weight", "attentions.15.k_lin.bias", "attentions.15.v_lin.weight", "attentions.15.v_lin.bias", "attentions.15.out_lin.weight", "attentions.15.out_lin.bias", "layer_norm1.12.weight", "layer_norm1.12.bias", "layer_norm1.13.weight", "layer_norm1.13.bias", "layer_norm1.14.weight", "layer_norm1.14.bias", "layer_norm1.15.weight", "layer_norm1.15.bias", "ffns.12.lin1.weight", "ffns.12.lin1.bias", "ffns.12.lin2.weight", "ffns.12.lin2.bias", "ffns.13.lin1.weight", "ffns.13.lin1.bias", "ffns.13.lin2.weight", "ffns.13.lin2.bias", "ffns.14.lin1.weight", "ffns.14.lin1.bias", "ffns.14.lin2.weight", "ffns.14.lin2.bias", "ffns.15.lin1.weight", "ffns.15.lin1.bias", "ffns.15.lin2.weight", "ffns.15.lin2.bias", "layer_norm2.12.weight", "layer_norm2.12.bias", "layer_norm2.13.weight", "layer_norm2.13.bias", "layer_norm2.14.weight", "layer_norm2.14.bias", "layer_norm2.15.weight", "layer_norm2.15.bias".

Do you have any suggestion to what may be triggering the error?

**Comment by him-mah10** [comment]
@shaunlim0105 did you figure this out? I am stuck with same error.

**Comment by lyysl** [comment]
I also have the unexpected keys for attentions. Anyone knows the solutions? Thank you!

**Comment by aloka-fernando** [comment]
I also have the same error. 

I want to do a continual pre-training on the released xlmr model (mlm_100_1280.pth) using the bilingual dataset en-si.

I have used the Paracrawl en-si parallel data, and learnt the BPE codes , vocabulary (as per XLM-R Readme.md) and pre-preprocessed (binarized) the data.

Please let me know whether using own BPE codes and vocab work during my scenario.....or else I need to use the XLM-R  BPE code and vocab. If this is the case please share with me on links to download this. 

The data path contains the files as follows.
```python
test.en.pth        test.en-si.si.pth  train.en.pth        train.en-si.si.pth  valid.en.pth        valid.en-si.si.pth
test.en-si.en.pth  test.si.pth        train.en-si.en.pth  train.si.pth        valid.en-si.en.pth  valid.si.pth

```
Training command as follows:

```python
DATAPATH="data/processed/xlmr_en_si/50k"

python train.py \
--exp_name exp07 \
--dump_path './experiments/xlmr_pretraining' \
--exp_id run1 \
--reload_model './pre_trained_models/mlm_100_1280.pth' \
--data_path $DATAPATH \
--mlm_steps 'en,si,en-si' \
--lgs 'en-si'  \
--clm_steps ''  \
--emb_dim 1280  \
--n_layers 12  \
--n_heads 16   \
--dropout 0.1 \
--attention_dropout 0.1  \
--gelu_activation true  \
--batch_size 8  \
--bptt 256     \
--optimizer "adam,lr=0.0001" \
--epoch_size 100000 \
--max_epoch 5 \
--max_vocab 200000 \
--word_mask_keep_rand '0.8,0.1,0.1' \
--validation_metrics _valid_mlm_ppl \
--stopping_criterion _valid_mlm_ppl,25 

```
Error
-------

```python
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 234, in main
    model = build_model(params, data['dico'])
  File "/content/drive/MyDrive/ColabNotebooks/p31_cross_lingual_representation_improvement/xlm/xlm/model/__init__.py", line 134, in build_model
    model.load_state_dict(reloaded)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Missing key(s) in state_dict: "lang_embeddings.weight". 
	Unexpected key(s) in state_dict: "attentions.12.q_lin.weight", "attentions.12.q_lin.bias", "attentions.12.k_lin.weight", "attentions.12.k_lin.bias", "attentions.12.v_lin.weight", "attentions.12.v_lin.bias", "attentions.12.out_lin.weight", "attentions.12.out_lin.bias", "attentions.13.q_lin.weight", "attentions.13.q_lin.bias", "attentions.13.k_lin.weight", "attentions.13.k_lin.bias", "attentions.13.v_lin.weight", "attentions.13.v_lin.bias", "attentions.13.out_lin.weight", "attentions.13.out_lin.bias", "attentions.14.q_lin.weight", "attentions.14.q_lin.bias", "attentions.14.k_lin.weight", "attentions.14.k_lin.bias", "attentions.14.v_lin.weight", "attentions.14.v_lin.bias", "attentions.14.out_lin.weight", "attentions.14.out_lin.bias", "attentions.15.q_lin.weight", "attentions.15.q_lin.bias", "attentions.15.k_lin.weight", "attentions.15.k_lin.bias", "attentions.15.v_lin.weight", "attentions.15.v_lin.bias", "attentions.15.out_lin.weight", "attentions.15.out_lin.bias", "layer_norm1.12.weight", "layer_norm1.12.bias", "layer_norm1.13.weight", "layer_norm1.13.bias", "layer_norm1.14.weight", "layer_norm1.14.bias", "layer_norm1.15.weight", "layer_norm1.15.bias", "ffns.12.lin1.weight", "ffns.12.lin1.bias", "ffns.12.lin2.weight", "ffns.12.lin2.bias", "ffns.13.lin1.weight", "ffns.13.lin1.bias", "ffns.13.lin2.weight", "ffns.13.lin2.bias", "ffns.14.lin1.weight", "ffns.14.lin1.bias", "ffns.14.lin2.weight", "ffns.14.lin2.bias", "ffns.15.lin1.weight", "ffns.15.lin1.bias", "ffns.15.lin2.weight", "ffns.15.lin2.bias", "layer_norm2.12.weight", "layer_norm2.12.bias", "layer_norm2.13.weight", "layer_norm2.13.bias", "layer_norm2.14.weight", "layer_norm2.14.bias", "layer_norm2.15.weight", "layer_norm2.15.bias". 
	size mismatch for embeddings.weight: copying a param with shape torch.Size([200000, 1280]) from checkpoint, the shape in current model is torch.Size([87051, 1280]).
	size mismatch for pred_layer.proj.weight: copying a param with shape torch.Size([200000, 1280]) from checkpoint, the shape in current model is torch.Size([87051, 1280]).
	size mismatch for pred_layer.proj.bias: copying a param with shape torch.Size([200000]) from checkpoint, the shape in current model is torch.Size([87051]).
```

Can someone please suggest how to overcome this?
@glample appreciate your comments on resolving this.
