### ISSUE TITLE
AssertionError in pretraining step

### ISSUE THREAD

**Issue by lihongzheng-nlp** [facebookresearch/XLM#293]
Hello @aconneau and @glample , I want to train UNMT with two single monolingual dataset (Chinese and Vietnamese), after preprocessing the data with fastBPE respectively, I got the data structure:
zh-vi-wiki
    ├── codes.vi
    ├── codes.zh
    ├── test.vi
    ├── test.vi.pth
    ├── test.zh
    ├── test.zh.pth
    ├── train.vi
    ├── train.vi.pth
    ├── train.zh
    ├── train.zh.pth
    ├── valid.vi
    ├── valid.vi.pth
    ├── valid.zh
    ├── valid.zh.pth
    ├── vocab.vi
    ├── vocab.zh

Then I ran the following command lines:
`CUDA_VISIBLE_DEVICES=1 python train.py --exp_name wiki_mlm --dump_path dumped/ --data_path ~/data/zh-vi-wiki/ --lgs 'vi-zh' --mlm_steps 'vi,zh' --emb_dim 512 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --batch_size 32 --bptt 256 --optimizer adam,lr=0.0001 --epoch_size 20000 --validation_metrics _valid_mlm_ppl --stopping_criterion _valid_mlm_ppl,10`

But when loading the Chinese data, I got the errors:
`INFO - 04/26/20 01:06:09 - 0:00:01 - ============ Monolingual data (zh)
INFO - 04/26/20 01:06:09 - 0:00:01 - Loading data from /home/hzli/data/zh-vi-wiki/train.zh.pth ...
INFO - 04/26/20 01:06:09 - 0:00:01 - 48141962 words (57187 unique) in 1766702 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 230, in main
    data = load_data(params)
  File "/home/hzli/work/facebook_toolkits/XLM/src/data/loader.py", line 334, in load_data
    load_mono_data(params, data)
  File "/home/hzli/work/facebook_toolkits/XLM/src/data/loader.py", line 127, in load_mono_data
    set_dico_parameters(params, data, mono_data['dico'])
  File "/home/hzli/work/facebook_toolkits/XLM/src/data/loader.py", line 78, in set_dico_parameters
    assert data['dico'] == dico
AssertionError`
And attached is the training log for reference.

 I also tried to preprocess the two language data together, such as `fast learnbpe 40000 train.vi train.zh > codes`, but it failed again and again, with the same error above. Would you please help me solve the confusing problem? Thank you very much!
[monolingual-train.log](https://github.com/facebookresearch/XLM/files/4533702/monolingual-train.log)

**Comment by lihongzheng-nlp** [comment]
Oh, so sorry for bothering. I made a stupid mistake, that I  entered the wrong data path……

**Comment by LetsGoFir** [comment]
I meet the same problem,, and how do you fix it?
