### ISSUE TITLE
Error in multi-bleu.perl in calculating BLEU score while MT training

### ISSUE THREAD

**Issue by abdullahkhilji** [facebookresearch/XLM#300]
```
Use of uninitialized value in division (/) at multi-bleu.perl line 139, <STDIN> line 1000.
```

**Comment by garyhsu29** [comment]
Hello, did you solve this problem? I have the same problem! Thanks!

**Comment by abdullahkhilji** [comment]
Yes, if the values are too small or BLEU 4 is 0 it reports an error. Maybe it is due to presence of <UNK> formed due to improper vocab.
