### ISSUE TITLE
Question About Performance

### ISSUE THREAD

**Issue by cocaer** [facebookresearch/XLM#33]
The paper shows the best en-fr bleu is 33.4. The readme.md shows 
'epoch               ->     7
valid_fr-en_mt_bleu -> 28.36
valid_en-fr_mt_bleu -> 30.50
test_fr-en_mt_bleu  -> 34.02
test_en-fr_mt_bleu  -> 36.62'.
Does this result form the max_len parameter which removes the long sentences from parallel  test corpus?

**Comment by glample** [comment]
No, the difference comes from the fact that the monolingual dataset is different. In the paper we use all NewsCrawl, in the Github we just use NewsCrawl 2013 and 2014 I believe, which is more in domain with newstest2014 on which we evaluate.

**Comment by teslacool** [comment]
hi, @glample . I have some questions on the monolingual data and in my preliminary work I found that selection of in-domain data is also critical to UNMT. 

You said the number 36.62 is run on   NewsCrawl 2013 and 2014 in the github, but in [get-data-nmt.sh](https://github.com/facebookresearch/XLM/blob/4e56d746e495f9ead735aa4710bfd94b872eb778/get-data-nmt.sh#L174) this is from 07 and 08. Maybe it is a bit different.

Or do you have any more detailed methods for selecting data?
