### ISSUE TITLE
loss of paddding

### ISSUE THREAD

**Issue by JiqiangLiu** [facebookresearch/XLM#34]
Hi, do we need to ignore padding's loss when we do back-translation? It seems that the code doesn't ignore the padding when we calculate loss. Thank you very much.
https://github.com/facebookresearch/XLM/blob/14fe2d467987f4a9eed9e209cec35b59f79ca0c8/src/trainer.py#L824

**Comment by glample** [comment]
We do no? This line is supposed to set to 0 everything that is longer than sentences in `x1`, i.e. padding.

**Comment by JiqiangLiu** [comment]
Ah, right. I got. Thanks.
