### ISSUE TITLE
unsupervised NMT 

### ISSUE THREAD

**Issue by odel-odel** [facebookresearch/XLM#35]

**Comment by odel-odel** [comment]
Is it possible to train the UNMT with all the 15 languagues of the XNLI together? 
Or I need to train pairs of languagues each time ?
If not,
Is it possible to give to the train of NMT the XNLI15 instead of the XNLI pair of the specific pair that we train in NMT?

**Comment by glample** [comment]
Yes, you can train anything on as many languages as you want, for an arbitrary number of directions. You can for instance do: `--mt_steps "en-fr,de-zh,hi-ur"` etc. and something similar for `--bt_steps`.
