### ISSUE TITLE
Memory is not released

### ISSUE THREAD

**Issue by JiqiangLiu** [facebookresearch/XLM#40]
Hi, when the program ends, the memory of the GPU0 is released, but the other GPUs are not released. Why that ?

**Comment by glample** [comment]
It has to be released. If you check the process ID with nvidia-smi you will see the process ID of the job which is still using memory, and it's probably some other process using the GPU 0.

**Comment by StillKeepTry** [comment]
In fact, I also meet this problem. I directly kill these processes manually.

**Comment by JiqiangLiu** [comment]
Thanks. It is easy way to solve this problem.
