### ISSUE TITLE
Translation script

### ISSUE THREAD

**Issue by rbawden** [facebookresearch/XLM#42]
Hello! Do you happen to have a translate.py script so that the model can be used to translate new data? I saw the `--eval_only` parameter, but it seems that the file to be translated has to be named according to the naming conventions specified in the trainer (and the data folder has to contain all the training/validation files too). The evaluator also appears to be using the target language file to get the maximum sentence length, which we shouldn't have access to when translating a new document.

Thanks for your help!

**Comment by kirefu** [comment]
+1

**Comment by glample** [comment]
Hi,

I'll work on this tonight or tomorrow, and add a script to do that.

**Comment by glample** [comment]
Here it is: https://github.com/facebookresearch/XLM/commit/97aeb8dcddcfcaa4a081754bcd238a51b11e6613

Usage:
```
cat source_sentences.bpe | \
python translate.py --exp_name translate \
--model_path trained_model.pth \
--output_path output\
--src_lang en --tgt_lang fr --batch_size 32
```

**Comment by rbawden** [comment]
Great, thank you!

**Comment by KelleyYin** [comment]
> Here it is: [97aeb8d](https://github.com/facebookresearch/XLM/commit/97aeb8dcddcfcaa4a081754bcd238a51b11e6613)
> 
> Usage:
> 
> ```
> cat source_sentences.bpe | \
> python translate.py --exp_name translate \
> --model_path trained_model.pth \
> --output_path output \
> --src_lang en --tgt_lang fr --batch_size 32
> ```

Can I use beam decoding and add some other parameters (eg., length penalty) during decoding ?

**Comment by glample** [comment]
Yes, all is implemented, see for instance https://github.com/facebookresearch/XLM/blob/master/train.py#L174-L180

Then the only thing to do is to give these parameters as input to https://github.com/facebookresearch/XLM/blob/master/translate.py#L117
