### ISSUE TITLE
Sentence delimiter <s> or </s>

### ISSUE THREAD

**Issue by korakot** [facebookresearch/XLM#43]
I look into the notebook to embed a sentence.

https://github.com/facebookresearch/XLM/blob/master/generate-embeddings.ipynb

In the cell `In[6]` there is this code.

`sentences = [(('</s> %s </s>' % sent.strip()).split(), lang) for sent, lang in sentences]`

Isn't it supposed to be '&lt;s> %s &lt;/s>' instead? Do I misunderstand something?

**Comment by glample** [comment]
No, this is correct. In the case of language model training, sentences are attached one after each other in a stream. A stream looks like:
```
</s> sent_1_word_1 sent_1_word_2 ... sent_1_word_n </s> sent_2_word_1 sent_2_word_2 ... sent_2_word_m </s> sent_3_word_1 ...
```
In that setting, the model learns that the </s> is used to both delimitate the beginning and the end of a sentence.

**Comment by JiqiangLiu** [comment]
@glample Hi, what are the advantages of doing this ？Thank you.

**Comment by glample** [comment]
I think this was the simplest way to combine MLM / CLM and MT training. It probably does not make a big difference as it should be easy for the model to understand the meaning of these symbols.
