### ISSUE TITLE
Why SRC < TGT ?

### ISSUE THREAD

**Issue by mamprogr** [facebookresearch/XLM#44]
https://github.com/facebookresearch/XLM/blob/14fe2d467987f4a9eed9e209cec35b59f79ca0c8/get-data-nmt.sh#L52

Hi @glample,
Can you explain why do you make this assumption "SRC < TGT"?
I noticed it also in:
https://github.com/facebookresearch/XLM/blob/14fe2d467987f4a9eed9e209cec35b59f79ca0c8/src/data/loader.py#L307 https://github.com/facebookresearch/XLM/blob/14fe2d467987f4a9eed9e209cec35b59f79ca0c8/src/evaluation/evaluator.py#L76 https://github.com/facebookresearch/XLM/blob/14fe2d467987f4a9eed9e209cec35b59f79ca0c8/src/evaluation/evaluator.py#L95

**Comment by glample** [comment]
This is just some convention to avoid the code to load both an English-French parallel dataset along with a French-English parallel dataset which would be exactly identical.

**Comment by mamprogr** [comment]
Thank you for the clarification.
