### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by rbawden** [facebookresearch/XLM#48]
Hello! I have been running your translate.py script and have been running into this error on a particular line of my input file, containing a BPE-ised URL but other than that nothing particular (only 13 subwords long) The error occurs with the following line of code:

`decoded,` dec_lengths = decoder.generate(encoded, lengths.cuda(), params.tgt_id, max_len=int(1.5 * lengths.max().item() + 10))`

Do you have any suggestions about what might be causing this error and how it could be fixed? Thank you very much in advance!

**Comment by glample** [comment]
Do you have the full traceback?

This looks like some out of bounds error, i.e. there is a word index which is higher than the number of embeddings or something. Can you try to add `CUDA_LAUNCH_BLOCKING=1` in front of your command to have a more detailed error message? If you can try to run the model on CPU you would probably get a more explicit error message as well.

**Comment by rbawden** [comment]
Yes, here's the trace book (from `CUDA_LAUNCH_BLOCKING=1`:

```
Traceback (most recent call last):
  File "/home/username/tools/XLM/translate.py", line 150, in <module>
    main(params)
  File "/home/username/tools/XLM/translate.py", line 115, in main
    encoded = encoder('fwd', x=batch.cuda(), lengths=lengths.cuda(), langs=langs.cuda(), causal=False)
  File "/home/username/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/username/tools/XLM/src/model/transformer.py", line 311, in forward
    return self.fwd(**kwargs)
  File "/home/username/tools/XLM/src/model/transformer.py", line 369, in fwd
    tensor = tensor + self.position_embeddings(positions).expand_as(tensor)
RuntimeError: CUDA error: device-side assert triggered
```

Could this be due to the way unknown words are handled?

Thank you!

**Comment by glample** [comment]
How long are your sequences? The position embeddings does not seem to contain enough positions. By default it contains 512 positions: https://github.com/facebookresearch/XLM/blob/master/src/model/transformer.py#L17

Try to replace this value by 1024 if you are using larger sequences, it should fix the issue.

**Comment by rbawden** [comment]
Yes, thank you! There was a long sentence in the next batch, so I've filtered out sentences that are too long now. It's all running fine again!

**Comment by bhardwaj1230** [comment]
> How long are your sequences? The position embeddings does not seem to contain enough positions. By default it contains 512 positions: https://github.com/facebookresearch/XLM/blob/master/src/model/transformer.py#L17
> 
> Try to replace this value by 1024 if you are using larger sequences, it should fix the issue.

Thank you for this, I was strggling with this issue for long.
