### ISSUE TITLE
 Address already in use

### ISSUE THREAD

**Issue by cocaer** [facebookresearch/XLM#53]
I tried to run several multi-gpu programs on a single server.But I countered this problem
`
RuntimeError: Address already in use at /pytorch/torch/lib/THD/process_group/General.cpp:17
`
So, if I have 4 GPUS on a single server and want to run two programs on GPU 0,1 and 2,3, how can I set the  parameter local_rank and master_port? @glample

**Comment by cocaer** [comment]
In slurm.py, I change like this,
`
    elif params.local_rank != -1:
        #assert params.master_port == -1
        os.environ['MASTER_PORT'] = str(params.master_port)
`
and set --master_port to any free port.
Then it works well.

**Comment by Dolprimates** [comment]
Which line of slurm.py did you change?

**Comment by cocaer** [comment]
hi, @Dolprimates https://github.com/facebookresearch/XLM/blob/e3055c008c2fa21510508a9e4e463d915cd031a1/src/slurm.py#L105

**Comment by Dolprimates** [comment]
What is the argument of the option --master_port?

**Comment by cocaer** [comment]
@Dolprimates  see train.py https://github.com/facebookresearch/XLM/blob/e3055c008c2fa21510508a9e4e463d915cd031a1/train.py#L197 
I think it's gpus  communication port.

**Comment by Dolprimates** [comment]
So, in order to set --master_port any free port, what do you write after --master_port?

`--master_port  XXXX`

**Comment by cocaer** [comment]
--master_port 32000. Any free port is ok.
