### ISSUE TITLE
Is there a plan releasing the XNLI-15 MLM model?

### ISSUE THREAD

**Issue by MengZou0905** [facebookresearch/XLM#54]
Hi, thanks for your work. Can you also release the XNLI-15 model trained only with mlm objective?

**Comment by Demonji** [comment]
@MengZou0905 预训练的XNLI-15 TLM 您使用过吗？ 为什么我下载词表之后，发现维度对不上。词表大小是121328，但是预训练的词表大小是95000。
谢谢！

**Comment by MengZou0905** [comment]
> @MengZou0905 预训练的XNLI-15 TLM 您使用过吗？ 为什么我下载词表之后，发现维度对不上。词表大小是121328，但是预训练的词表大小是95000。
> 谢谢！
抱歉，我还没有使用过TLM模型，不太清楚。

**Comment by aconneau** [comment]
We will release larger models with MLM-only soon. Stay tuned.

**Comment by aconneau** [comment]
Please refer to the README. The model is already there. We will release additional XLM models in the future.
