### ISSUE TITLE
Question About Decoder

### ISSUE THREAD

**Issue by cocaer** [facebookresearch/XLM#55]
How does the decoder know which direction go towards(lang1 or lang2) when input language is lang1?In other words, how does the decoder know which state it is at , DAE or MT ?
In the previous  version(UNMT), it uses different project layers. In XLM, `self.pred_layer` is always same. @glample

**Comment by glample** [comment]
I'm not sure I understand the question. The setup here is the same as in UNMT, the language ID defines what language the model is encoding or decoding.
In UNMT it was a bit different, the language ID was only used to define the start symbol (i.e. <s_en>, <s_fr>, etc.) while here there is just one start symbol <s> and a language embedding is added at every timestep.

**Comment by cocaer** [comment]
@glample Sorry for my poor expression in English. I want to ensure that the only difference between in DAE step and Mt step is the language embedding. For example ,to train en->en, decoder will add en language [embedding.](https://github.com/facebookresearch/XLM/blob/34825ea305aac1d9d87a33a7a9d3069fb8aca87d/src/model/transformer.py#L371) For en->fr, deocder will add fr language embedding. Is this the only difference and does language embedding  play the  crucial role in decode direction?

**Comment by glample** [comment]
Yes, you are correct. The only difference between en->en and en->fr is the language embedding given as input to the decoder.
