### ISSUE TITLE
Is MLM essential to MLM+TLM?

### ISSUE THREAD

**Issue by yilinyang7** [facebookresearch/XLM#59]
Dear authors,

Thanks for the great work. I just wonder if you guys have tried to remove MLM from MLM+TLM to see the differences. Because BERT is essentially trained with masked next_sentence_prediction, as a comparison, is TLM alone enough?

**Comment by glample** [comment]
Yes, I think TLM alone would probably be enough, but MLM is helpful I think as it trains the model to have extremely long range dependencies, as in MLM you can find training corpora like Wikipedia or Toronto Book Corpus where the sentences are continuous, and with MLM you train on streams of sentences so the model is encouraged to look very far in the past / future to predict masked words.
But training at sentence level is also fine (this is more or less what BERT does after all), so I think TLM alone should be enough.

**Comment by yilinyang7** [comment]
Thanks for your insights :)
