### ISSUE TITLE
Mismatch for processed vocab size and pretrained model size

### ISSUE THREAD

**Issue by Demonji** [facebookresearch/XLM#61]
@glample  I download the vocab size by
`wget -c https://dl.fbaipublicfiles.com/XLM/vocab_xnli_15`
then i download the pretraining model by
`wget -c https://dl.fbaipublicfiles.com/XLM/mlm_tlm_xnli15_1024.pth`

Then the error is 
`	size mismatch for embeddings.weight: copying a param of torch.Size([121328, 1024]) from checkpoint, where the shape is torch.Size([95000, 1024]) in current model.
`.
It seems that processed vocab size does't  equal to pretrained model size.

**Comment by VolantBoy** [comment]
@glample same question

**Comment by glample** [comment]
Can you try to add the parameter: `--max_vocab 95000` ?

**Comment by rajenchatterjee** [comment]
"--max_vocab 95000" did solve the problem for me
