### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for TransformerModel

### ISSUE THREAD

**Issue by qtxue** [facebookresearch/XLM#62]
![image](https://user-images.githubusercontent.com/45347244/56464842-563dc600-6424-11e9-9405-2450f819ec5a.png)
I run the Unsupervised NMT on en-fr by using the provided pretrained language model,and I haven't change anything include the step of run the get-data-nmt.sh. what is the reason of the dim error like the picture show above.

**Comment by glample** [comment]
Did you run exactly these commands?

```
wget https://dl.fbaipublicfiles.com/XLM/codes_enfr
wget https://dl.fbaipublicfiles.com/XLM/vocab_enfr

./get-data-nmt.sh --src en --tgt fr --reload_codes codes_enfr --reload_vocab vocab_enfr
```

There are 64125 lines in vocab_enfr, so the dictionary size should be 64125 + 14 (14 for the special symbols reserved by the model) = 64139, which is the size of the embeddings in the checkpoint, as it is visible in your error message. Please verify that the `codes_enfr` and `vocab_enfr` are exactly the ones you are using in your preprocessing script, and don't hesitate to retry the preprocessing from scratch, as some data may not be re-generated if it has been generated with the wrong vocabulary in a previous run.

**Comment by amritbhaskar** [comment]
I checked with vocab_enfr . It has 64125 lines, but i got the same error as stated above by 'qtxue'.

**Comment by glample** [comment]
Mm this is not normal. Can you show me the full log of the command `get-data-nmt.sh`?

**Comment by qtxue** [comment]
you are right, at first, I run the `get-data-nmt.sh` with the command:`./get-data-nmt.sh --src en --tgt fr`, the vocab size are different. there are only 60360 lines in vocab.en-fr. And then, I retry the preprocessing as you said, The problem has disappeared. Now, I have another question, Do I have to use exactly the same parameters setting as yours, if I use the pretrianed model `mlm_enfr_1024.pth`? such as the 1024 emd dim and 6 n_layers,etc.

**Comment by glample** [comment]
If you want to reload `mlm_enfr_1024.pth` yes you will need to use the same vocabulary, otherwise you won't be able to reload the lookup table (maybe you can reload the other layers for pretraining, but not sure how it will perform), and you definitely need the same model dimension 1024. Now if you want to have 12 layers you can pretrain the 6 first with `mlm_enfr_1024.pth` and finetune the others but it may not work as well as if you train everything from scratch. In that case I would suggest to pretrain only the embeddings.

**Comment by amritbhaskar** [comment]
Extracting parallel data...
Tokenizing valid and test data...
Tokenizer Version 1.1
Language: en
Number of threads: 16
Tokenizer Version 1.1
Language: fr
Number of threads: 16
Tokenizer Version 1.1
Language: en
Number of threads: 16
Tokenizer Version 1.1
Language: fr
Number of threads: 16
Applying BPE to valid and test files...
Loading vocabulary from /home/kollis/amrit/XLM-master/data/processed/en-fr/vocab.en ...
Read 128885967 words (45297 unique) from vocabulary file.
Loading codes from /home/kollis/amrit/XLM-master/data/processed/en-fr/codes ...
Read 60000 codes from the codes file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/para/dev/newstest2013-ref.en ...
Read 64812 words (9678 unique) from text file.
Applying BPE to /home/kollis/amrit/XLM-master/data/para/dev/newstest2013-ref.en ...
Modified 64812 words from text file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/processed/en-fr/vocab.fr ...
Read 130136566 words (53617 unique) from vocabulary file.
Loading codes from /home/kollis/amrit/XLM-master/data/processed/en-fr/codes ...
Read 60000 codes from the codes file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/para/dev/newstest2013-ref.fr ...
Read 73672 words (11057 unique) from text file.
Applying BPE to /home/kollis/amrit/XLM-master/data/para/dev/newstest2013-ref.fr ...
Modified 73672 words from text file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/processed/en-fr/vocab.en ...
Read 128885967 words (45297 unique) from vocabulary file.
Loading codes from /home/kollis/amrit/XLM-master/data/processed/en-fr/codes ...
Read 60000 codes from the codes file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/para/dev/newstest2014-fren-ref.en ...
Read 71150 words (10609 unique) from text file.
Applying BPE to /home/kollis/amrit/XLM-master/data/para/dev/newstest2014-fren-ref.en ...
Modified 71150 words from text file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/processed/en-fr/vocab.fr ...
Read 130136566 words (53617 unique) from vocabulary file.
Loading codes from /home/kollis/amrit/XLM-master/data/processed/en-fr/codes ...
Read 60000 codes from the codes file.
Loading vocabulary from /home/kollis/amrit/XLM-master/data/para/dev/newstest2014-fren-ref.fr ...
Read 81101 words (11721 unique) from text file.
Applying BPE to /home/kollis/amrit/XLM-master/data/para/dev/newstest2014-fren-ref.fr ...
Modified 81101 words from text file.
Binarizing data...
INFO - 04/22/19 17:33:48 - 0:00:00 - Read 60374 words from the vocabulary file.

Saving the data to /home/kollis/amrit/XLM-master/data/processed/en-fr/valid.en-fr.en.pth ...
INFO - 04/22/19 17:33:48 - 0:00:00 - 69930 words (60374 unique) in 3000 sentences.
INFO - 04/22/19 17:33:48 - 0:00:00 - 1 unknown words (1 unique), covering 0.00% of the data.
INFO - 04/22/19 17:33:48 - 0:00:00 - |: 1
INFO - 04/22/19 17:33:49 - 0:00:00 - Read 60374 words from the vocabulary file.

Saving the data to /home/kollis/amrit/XLM-master/data/processed/en-fr/valid.en-fr.fr.pth ...
INFO - 04/22/19 17:33:49 - 0:00:00 - 80140 words (60374 unique) in 3000 sentences.
INFO - 04/22/19 17:33:49 - 0:00:00 - 15 unknown words (8 unique), covering 0.02% of the data.
INFO - 04/22/19 17:33:49 - 0:00:00 - Č@@: 5
INFO - 04/22/19 17:33:49 - 0:00:00 - č: 2
INFO - 04/22/19 17:33:49 - 0:00:00 - ď@@: 2
INFO - 04/22/19 17:33:49 - 0:00:00 - ů@@: 2
INFO - 04/22/19 17:33:49 - 0:00:00 - ň@@: 1
INFO - 04/22/19 17:33:49 - 0:00:00 - ń@@: 1
INFO - 04/22/19 17:33:49 - 0:00:00 - ž: 1
INFO - 04/22/19 17:33:49 - 0:00:00 - |: 1
INFO - 04/22/19 17:33:50 - 0:00:00 - Read 60374 words from the vocabulary file.

Saving the data to /home/kollis/amrit/XLM-master/data/processed/en-fr/test.en-fr.en.pth ...
INFO - 04/22/19 17:33:50 - 0:00:00 - 76386 words (60374 unique) in 3003 sentences.
INFO - 04/22/19 17:33:51 - 0:00:00 - Read 60374 words from the vocabulary file.

Saving the data to /home/kollis/amrit/XLM-master/data/processed/en-fr/test.en-fr.fr.pth ...
INFO - 04/22/19 17:33:51 - 0:00:00 - 87012 words (60374 unique) in 3003 sentences.

===== Data summary
Monolingual training data:
    en: /home/kollis/amrit/XLM-master/data/processed/en-fr/train.en.pth
    fr: /home/kollis/amrit/XLM-master/data/processed/en-fr/train.fr.pth
Monolingual validation data:
    en: /home/kollis/amrit/XLM-master/data/processed/en-fr/valid.en.pth
    fr: /home/kollis/amrit/XLM-master/data/processed/en-fr/valid.fr.pth
Monolingual test data:
    en: /home/kollis/amrit/XLM-master/data/processed/en-fr/test.en.pth
    fr: /home/kollis/amrit/XLM-master/data/processed/en-fr/test.fr.pth
Parallel validation data:
    en: /home/kollis/amrit/XLM-master/data/processed/en-fr/valid.en-fr.en.pth
    fr: /home/kollis/amrit/XLM-master/data/processed/en-fr/valid.en-fr.fr.pth
Parallel test data:
    en: /home/kollis/amrit/XLM-master/data/processed/en-fr/test.en-fr.en.pth
    fr: /home/kollis/amrit/XLM-master/data/processed/en-fr/test.en-fr.fr.pth


Please suggest a solution. @glample

**Comment by glample** [comment]
From the log file it does not look like you are using the vocabulary file. If you look at: https://github.com/facebookresearch/XLM/blob/master/get-data-nmt.sh#L300-L305 you see the model vocabulary, as you should be seeing `Reloading vocabulary from ....`  Same for the BPE codes here: https://github.com/facebookresearch/XLM/blob/master/get-data-nmt.sh#L265-L270

Can you try again with the vocabulary? Maybe the provided path is incorrect or something. Also, given the log it looks like maybe you commented out a part of the preprocessing script to only take into account the parallel data? The problem being that the script that reloads the BPE codes / vocabulary is in the monolingual preprocessing.
