### ISSUE TITLE
Training with less GPU

### ISSUE THREAD

**Issue by PC09** [facebookresearch/XLM#64]
Is there a way to run train.py with less resource, like I have single machine with 2 GPUs- 12 and 4GB.

I am running the following code-
python train.py  --exp_name test_enfr_mlm   --dump_path ./dumped/    --data_path ./data/processed/en-fr/  --lgs 'en-fr'    --clm_steps ''  --mlm_steps 'en,fr' --emb_dim 1024   --n_layers 6    --n_heads 8   --dropout 0.1  --attention_dropout 0.1     --gelu_activation true   --batch_size 32    --bptt 256      --optimizer adam,lr=0.0001   --epoch_size 200000      --validation_metrics _valid_mlm_ppl   --stopping_criterion _valid_mlm_ppl,10

I am getting the following error:-

INFO - 04/24/19 12:34:48 - 0:00:14 - Creating new training data iterator (pred,fr) ...
/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : //
Traceback (most recent call last):
  File "train.py", line 342, in <module>
    main(params)
  File "train.py", line 294, in main
    trainer.mlm_step(lang1, lang2, params.lambda_mlm)
  File "/home/kollis/Parul/XLM-master/src/trainer.py", line 627, in mlm_step
    self.optimize(loss, name)
  File "/home/kollis/Parul/XLM-master/src/trainer.py", line 130, in optimize
    loss.backward()
  File "/home/kollis/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/kollis/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 280.38 MiB (GPU 0; 11.17 GiB total capacity; 10.38 GiB already allocated; 97.69 MiB free; 380.07 MiB cached)

When I observe the GPU usage, the 12 GB resource gets exhausted and thus the error pops up.

**Comment by glample** [comment]
4GB is very small, I dont think you can train the model with that, the model itself with its optimizers states will not be far from 4GB, and in the transformer the activations are what use the most memory. With 12GB you should not have any issues, you maybe just need to reduce the batch size.

**Comment by PC09** [comment]
Thanks @glample , by reducing the batch size , I am able to start training. If I skip training and directly use your pretrained model (wget -c https://dl.fbaipublicfiles.com/XLM/mlm_enfr_1024.pth) for unsupervised NMT , I am getting CUDA memmory exhaust error. I am not able to load the model and start training even with reduced batch size.

The command I am running,

python train.py --exp_name unsupMT_enfr --dump_path ./dumped/ --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path ./data/processed/en-fr/  --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 2 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 2000 --batch_size 4 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 5000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu'

Error log-

SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : kollis-CTO
INFO - 04/24/19 16:49:26 - 0:00:00 - ============ Initialized logger ============
INFO - 04/24/19 16:49:26 - 0:00:00 - ae_steps: ['en', 'fr']
                                     asm: False
                                     attention_dropout: 0.1
                                     batch_size: 4
                                     beam_size: 1
                                     bptt: 256
                                     bt_src_langs: ['en', 'fr']
                                     bt_steps: [('en', 'fr', 'en'), ('fr', 'en', 'fr')]
                                     clip_grad_norm: 5
                                     clm_steps: []
                                     command: python train.py --exp_name unsupMT_enfr --dump_path './dumped/' --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path './data/processed/en-fr/' --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout '0.1' --word_blank '0.1' --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 2 --dropout '0.1' --attention_dropout '0.1' --gelu_activation true --tokens_per_batch 2000 --batch_size 4 --bptt 256 --optimizer 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001' --epoch_size 5000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu' --exp_id "t3uhggul4h"
                                     context_size: 0
                                     data_path: ./data/processed/en-fr/
                                     debug_slurm: False
                                     debug_train: False
                                     dropout: 0.1
                                     dump_path: ./dumped/unsupMT_enfr/t3uhggul4h
                                     early_stopping: False
                                     emb_dim: 1024
                                     encoder_only: False
                                     epoch_size: 5000
                                     eval_bleu: True
                                     eval_only: False
                                     exp_id: t3uhggul4h
                                     exp_name: unsupMT_enfr
                                     fp16: False
                                     gelu_activation: True
                                     global_rank: 0
                                     group_by_size: True
                                     id2lang: {0: 'en', 1: 'fr'}
                                     is_master: True
                                     is_slurm_job: False
                                     lambda_ae: 0:1,100000:0.1,300000:0
                                     lambda_bt: 1
                                     lambda_clm: 1
                                     lambda_mlm: 1
                                     lambda_mt: 1
                                     lambda_pc: 1
                                     lang2id: {'en': 0, 'fr': 1}
                                     langs: ['en', 'fr']
                                     length_penalty: 1
                                     lg_sampling_factor: -1
                                     lgs: en-fr
                                     local_rank: 0
                                     master_port: -1
                                     max_batch_size: 0
                                     max_epoch: 100000
                                     max_len: 100
                                     max_vocab: -1
                                     min_count: 0
                                     mlm_steps: []
                                     mono_dataset: {'en': {'train': './data/processed/en-fr/train.en.pth', 'valid': './data/processed/en-fr/valid.en.pth', 'test': './data/processed/en-fr/test.en.pth'}, 'fr': {'train': './data/processed/en-fr/train.fr.pth', 'valid': './data/processed/en-fr/valid.fr.pth', 'test': './data/processed/en-fr/test.fr.pth'}}
                                     mt_steps: []
                                     multi_gpu: False
                                     multi_node: False
                                     n_gpu_per_node: 1
                                     n_heads: 2
                                     n_langs: 2
                                     n_layers: 6
                                     n_nodes: 1
                                     node_id: 0
                                     optimizer: adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001
                                     para_dataset: {('en', 'fr'): {'valid': ('./data/processed/en-fr/valid.en-fr.en.pth', './data/processed/en-fr/valid.en-fr.fr.pth'), 'test': ('./data/processed/en-fr/test.en-fr.en.pth', './data/processed/en-fr/test.en-fr.fr.pth')}}
                                     pc_steps: []
                                     reload_checkpoint: 
                                     reload_emb: 
                                     reload_model: mlm_enfr_1024.pth,mlm_enfr_1024.pth
                                     sample_alpha: 0
                                     save_periodic: 0
                                     share_inout_emb: True
                                     sinusoidal_embeddings: False
                                     split_data: False
                                     stopping_criterion: valid_en-fr_mt_bleu,10
                                     tokens_per_batch: 2000
                                     validation_metrics: valid_en-fr_mt_bleu
                                     word_blank: 0.1
                                     word_dropout: 0.1
                                     word_keep: 0.1
                                     word_mask: 0.8
                                     word_mask_keep_rand: 0.8,0.1,0.1
                                     word_pred: 0.15
                                     word_rand: 0.1
                                     word_shuffle: 3.0
                                     world_size: 1
INFO - 04/24/19 16:49:26 - 0:00:00 - The experiment will be stored in ./dumped/unsupMT_enfr/t3uhggul4h
                                     
INFO - 04/24/19 16:49:26 - 0:00:00 - Running command: python train.py --exp_name unsupMT_enfr --dump_path './dumped/' --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path './data/processed/en-fr/' --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout '0.1' --word_blank '0.1' --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 2 --dropout '0.1' --attention_dropout '0.1' --gelu_activation true --tokens_per_batch 2000 --batch_size 4 --bptt 256 --optimizer 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001' --epoch_size 5000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu'

WARNING - 04/24/19 16:49:26 - 0:00:00 - Signal handler installed.
INFO - 04/24/19 16:49:26 - 0:00:00 - ============ Monolingual data (en)
INFO - 04/24/19 16:49:26 - 0:00:00 - Loading data from ./data/processed/en-fr/train.en.pth ...
INFO - 04/24/19 16:49:26 - 0:00:00 - 128885967 words (64139 unique) in 5000000 sentences. 755927 unknown words (4080 unique) covering 0.59% of the data.
INFO - 04/24/19 16:49:28 - 0:00:02 - Removed 0 empty sentences.
INFO - 04/24/19 16:49:28 - 0:00:02 - Removed 12756 too long sentences.

INFO - 04/24/19 16:49:28 - 0:00:02 - Loading data from ./data/processed/en-fr/valid.en.pth ...
INFO - 04/24/19 16:49:28 - 0:00:02 - 70197 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.

INFO - 04/24/19 16:49:28 - 0:00:02 - Loading data from ./data/processed/en-fr/test.en.pth ...
INFO - 04/24/19 16:49:28 - 0:00:02 - 76696 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.

INFO - 04/24/19 16:49:28 - 0:00:02 - ============ Monolingual data (fr)
INFO - 04/24/19 16:49:28 - 0:00:02 - Loading data from ./data/processed/en-fr/train.fr.pth ...
INFO - 04/24/19 16:49:29 - 0:00:03 - 130136566 words (64139 unique) in 5000000 sentences. 1472732 unknown words (5550 unique) covering 1.13% of the data.
INFO - 04/24/19 16:49:30 - 0:00:04 - Removed 0 empty sentences.
INFO - 04/24/19 16:49:30 - 0:00:04 - Removed 16151 too long sentences.

INFO - 04/24/19 16:49:30 - 0:00:04 - Loading data from ./data/processed/en-fr/valid.fr.pth ...
INFO - 04/24/19 16:49:30 - 0:00:04 - 80459 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.

INFO - 04/24/19 16:49:30 - 0:00:04 - Loading data from ./data/processed/en-fr/test.fr.pth ...
INFO - 04/24/19 16:49:30 - 0:00:04 - 87341 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.


INFO - 04/24/19 16:49:31 - 0:00:05 - ============ Parallel data (en-fr)
INFO - 04/24/19 16:49:31 - 0:00:05 - Loading data from ./data/processed/en-fr/valid.en-fr.en.pth ...
INFO - 04/24/19 16:49:31 - 0:00:05 - 70197 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.
INFO - 04/24/19 16:49:31 - 0:00:05 - Loading data from ./data/processed/en-fr/valid.en-fr.fr.pth ...
INFO - 04/24/19 16:49:31 - 0:00:05 - 80459 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.
INFO - 04/24/19 16:49:31 - 0:00:05 - Removed 0 empty sentences.

INFO - 04/24/19 16:49:31 - 0:00:05 - Loading data from ./data/processed/en-fr/test.en-fr.en.pth ...
INFO - 04/24/19 16:49:31 - 0:00:05 - 76696 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 04/24/19 16:49:31 - 0:00:05 - Loading data from ./data/processed/en-fr/test.en-fr.fr.pth ...
INFO - 04/24/19 16:49:31 - 0:00:05 - 87341 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 04/24/19 16:49:31 - 0:00:05 - Removed 0 empty sentences.


INFO - 04/24/19 16:49:31 - 0:00:05 - ============ Data summary
INFO - 04/24/19 16:49:31 - 0:00:05 - Monolingual data   - train -           en:   5000000
INFO - 04/24/19 16:49:31 - 0:00:05 - Monolingual data   - valid -           en:      3000
INFO - 04/24/19 16:49:31 - 0:00:05 - Monolingual data   -  test -           en:      3003
INFO - 04/24/19 16:49:31 - 0:00:05 - Monolingual data   - train -           fr:   5000000
INFO - 04/24/19 16:49:31 - 0:00:05 - Monolingual data   - valid -           fr:      3000
INFO - 04/24/19 16:49:31 - 0:00:05 - Monolingual data   -  test -           fr:      3003
INFO - 04/24/19 16:49:31 - 0:00:05 - Parallel data      - valid -        en-fr:      3000
INFO - 04/24/19 16:49:31 - 0:00:05 - Parallel data      -  test -        en-fr:      3003

INFO - 04/24/19 16:49:48 - 0:00:22 - Reloading encoder from mlm_enfr_1024.pth ...
/home/kollis/anaconda3/envs/amrit/lib/python3.6/site-packages/torch/cuda/__init__.py:117: UserWarning: 
    Found GPU1 Quadro K5000 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
INFO - 04/24/19 16:49:52 - 0:00:26 - Reloading decoder from mlm_enfr_1024.pth ...
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.0.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.0.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.q_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.q_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.k_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.k_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.v_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.v_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.out_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.0.out_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.1.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.1.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.q_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.q_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.k_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.k_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.v_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.v_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.out_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.1.out_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.2.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.2.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.q_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.q_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.k_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.k_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.v_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.v_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.out_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.2.out_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.3.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.3.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.q_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.q_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.k_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.k_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.v_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.v_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.out_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.3.out_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.4.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.4.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.q_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.q_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.k_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.k_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.v_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.v_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.out_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.4.out_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.5.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter layer_norm15.5.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.q_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.q_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.k_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.k_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.v_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.v_lin.bias not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.out_lin.weight not found.
WARNING - 04/24/19 16:49:53 - 0:00:27 - Parameter encoder_attn.5.out_lin.bias not found.
INFO - 04/24/19 16:49:53 - 0:00:27 - Number of parameters (encoder): 141848203
INFO - 04/24/19 16:49:53 - 0:00:27 - Number of parameters (decoder): 167050891
INFO - 04/24/19 16:49:55 - 0:00:29 - ============ Starting epoch 0 ... ============
INFO - 04/24/19 16:49:55 - 0:00:29 - Creating new training data iterator (ae,en) ...
/home/kollis/anaconda3/envs/amrit/lib/python3.6/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
INFO - 04/24/19 16:50:00 - 0:00:34 - Creating new training data iterator (ae,fr) ...
INFO - 04/24/19 16:50:05 - 0:00:39 - Creating new training data iterator (bt,en) ...
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 298, in main
    trainer.bt_step(lang1, lang2, lang3, params.lambda_bt)
  File "/home/kollis/amrit/XLM-master/src/trainer.py", line 840, in bt_step
    self.optimize(loss, ['encoder', 'decoder'])
  File "/home/kollis/amrit/XLM-master/src/trainer.py", line 130, in optimize
    loss.backward()
  File "/home/kollis/anaconda3/envs/amrit/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/kollis/anaconda3/envs/amrit/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 475.75 MiB (GPU 0; 11.17 GiB total capacity; 9.65 GiB already allocated; 297.44 MiB free; 917.80 MiB cached)


Please let me know if I am making any mistake or is it because of less resource. Is there a way to run it on 12GB. Also, what is the preferable cluster configuration to try this unsupervised NMT experiment.

**Comment by glample** [comment]
Can you also try to reduce `--tokens_per_batch 2000` ? When this parameter is set to something, the `batch_size` parameter is ignored, as the model tried to create batches with an arbitrary number of sentences, as long as their number of elements doesn't exceed 2000 tokens.

**Comment by jind11** [comment]
hey, Lample, I came across the same problem. I tried setting tokens_per_batch to 2000 but still got GPU out of memory problem for single 12 GB GPU. And even when I set the batch size to 1, I still got the same problem. I think the problem should come from the fact that there are a lot of warnings of not finding the parameter XXX as you can see from the last post by PC09. Could you help with this issue? Thanks!

**Comment by PC09** [comment]
Yes, @glample I also tried with reduced tokens_per_batch, but still the same error.

**Comment by glample** [comment]
@jind11 for machine translation, if you set the parameter tokens_per_batch to something, the parameter batch_size is ignored, so setting it to 1 won't change anything. I would have tried a smaller tokens_per_batch, maybe 1000 or something.

@PC09 do you have the same issue with a model of 6 layers dimension 512? What is the largest configuration from which you can start training?

**Comment by PC09** [comment]
Thanks @glample  I am able to start training on 8 GB system by reloading the pretrained model . I have set the tokens_per_batch parameter as 500
