### ISSUE TITLE
A little question about the target language and the language embedding.

### ISSUE THREAD

**Issue by xiami2019** [facebookresearch/XLM#68]
Hello, thanks for the share of your amazing work. I have a little question about the model in the translation step. I noticed that you use only one encoder , one decoder, one cross-lingual embedding and one cross-lingual lookup table for every language. So I'm confused that what decide the language of output sentence? Does the language embedding choose the language of the output sentence? And i didn't find the detail about the language embedding, could you please tell me what the language embedding's function here. Thank you very much!

**Comment by glample** [comment]
The language embedding is here https://github.com/facebookresearch/XLM/blob/master/src/model/transformer.py#L370-L371 and this is what will tell the model to decode into a specific language. For an encoded sentence that comes out of the encoder, you can decode it in English or French by providing either English or French language IDs to the decoder.

**Comment by xiami2019** [comment]
Got it. Thank you very much for your reply.


 
---Original---
