### ISSUE TITLE
About Translation problem

### ISSUE THREAD

**Issue by Daisy-123** [facebookresearch/XLM#69]
## I use this command line, as below : 

cat data/processed/XLM15/en.test.pth | /home/blue90211/anaconda3/bin/python translate.py --exp_name test --exp_id test_id --model_path mlm_tlm_xnli15_1024.pth --output_path test_out --src_lang en --tgt_lang zh

## but I got some problem like this :　

INFO - 05/03/19 16:37:34 - 0:00:00 - ============ Initialized logger ============
INFO - 05/03/19 16:37:34 - 0:00:00 - batch_size: 32
                                     command: python translate.py --exp_name test --exp_id test_id --model_path 'mlm_tlm_xnli15_1024.pth' --output_path test_out --src_lang en --tgt_lang zh --exp_id "test_id"
                                     dump_path: ./dumped/test/test_id
                                     exp_id: test_id
                                     exp_name: test
                                     fp16: False
                                     model_path: mlm_tlm_xnli15_1024.pth
                                     output_path: test_out
                                     src_lang: en
                                     tgt_lang: zh
INFO - 05/03/19 16:37:34 - 0:00:00 - The experiment will be stored in ./dumped/test/test_id

INFO - 05/03/19 16:37:34 - 0:00:00 - Running command: python translate.py --exp_name test --exp_id test_id --model_path 'mlm_tlm_xnli15_1024.pth' --output_path test_out --src_lang en --tgt_lang zh

INFO - 05/03/19 16:37:35 - 0:00:01 - Supported languages: ar, bg, de, el, en, es, fr, hi, ru, sw, th, tr, ur, vi, zh
Traceback (most recent call last):
  File "translate.py", line 150, in <module>
    main(params)
  File "translate.py", line 78, in main
    encoder = TransformerModel(model_params, dico, is_encoder=True, with_output=True).cuda().eval()
  File "/mnt/RAID/lxc_RAID/labsystem/blue90211/Translation/XLM/src/model/transformer.py", line 255, in __init__
    self.eos_index = params.eos_index
AttributeError: 'AttrDict' object has no attribute 'eos_index'

**Comment by cocaer** [comment]
mlm_tlm_xnli15_1024.pth is not a MT model.

**Comment by bohanbo** [comment]
I tried with the English-German model. It also gives me the same error.

cat test2.bpe | python translate.py --exp_name translate --src_lang de --tgt_lang en --model_path ./pretrained_model/deen/mlm_ende_1024.pth --output_path test_out

Error:

INFO - 05/31/19 14:03:36 - 0:00:00 - Supported languages: de, en
Traceback (most recent call last):
  File "translate.py", line 157, in <module>
    main(params)
  File "translate.py", line 75, in main
    setattr(params, name, getattr(model_params, name))
AttributeError: 'AttrDict' object has no attribute 'bos_index'


Any idea?
