### ISSUE TITLE
Unsupervised MT

### ISSUE THREAD

**Issue by MaryaAI** [facebookresearch/XLM#71]
I was wondering if there is a model trained on XNLI-15 for unsupervised MT?
it seems impossible to me to train the pretrained model right now, that I have AMD GPU and 6 GB RAM.

**Comment by glample** [comment]
Hi,

You can use the XNLI-15 for Unsupervised MT, but this is probably not optimal as the data was lowercased for that model, which is mainly designed for sentence classification.
