### ISSUE TITLE
Training UNMT model with XLM

### ISSUE THREAD

**Issue by odel-odel** [facebookresearch/XLM#74]

**Comment by odel-odel** [comment]
Hi,

I am trying to train UNMT model for three lang : **EN,FR,HI** with the basis of XNLI pretrain model 
my objective is to be able to use the translate script for translating sentences from **HI** to **EN** and from **FR** to **HI**  (for example)  

**the command I try to run is :**

 python3 train.py --exp_name unsupMT_XNLI --dump_path ./dumped/ --reload_model 'mlm_tlm_xnli15_1024.pth,mlm_tlm_xnli15_1024.pth' --data_path ./data/processed/XLM15/ --lgs 'en-fr-hi' --ae_steps 'en,fr,hi' --mt_steps 'en-hi,hi-en,fr-en,en-fr,hi-fr,fr-hi' --bt_steps 'en-fr-en,fr-en-fr,hi-en-hi,en-hi-en' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 1200 --batch_size 26  --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-hi_mt_bleu,10' --validation_metrics 'valid_en-hi_mt_bleu'

**but I  got this error ;**

Traceback (most recent call last):
  File "train.py", line 326, in <module>
    check_data_params(params)
  File "/NMT/XLM/src/data/loader.py", line 295, in check_data_params
    assert all([all([os.path.isfile(p) for p in paths.values()]) for paths in params.mono_dataset.values()])
AssertionError

the content of the XLM15 folder looks like this; ( with all the valid* and test* lang files...)

![image](https://user-images.githubusercontent.com/39080302/57363922-bfdf0380-718a-11e9-84da-6014032821f6.png)


Thanks in advance !

**Comment by glample** [comment]
`--mt_steps 'en-hi,hi-en,fr-en,en-fr,hi-fr,fr-hi'` means that you are doing supervised training in all those directions, which means that you have parallel data for English-Hindi, English-French, and French-Hindi. I would recommend downloading such datasets yourself instead of using the XNLI evaluation data which is pretty small. Then, you need to call these files "train.LANG.pth" otherwise the loader will not be able to find them.

**Comment by odel-odel** [comment]
Hi,
 so what should I run in order to get unsupervised mt  for those langauges based on XLM ?
Thanks,

**Comment by glample** [comment]
I would suggest downloading monolingual data in English, French and Hindi, and parallel data in English-French and English-Hindi. For English French you can use WMT for the parallel data, and NewsCrawl for the monolingual data. For everything related to Hindi, you can use: http://www.cfilt.iitb.ac.in/iitb_parallel/ They have a lot of monolingual and parallel data.

Then you can do something like:
`--mt_steps 'en-hi,hi-en,fr-en,en-fr'`
`--bt_steps 'fr-hi-fr,hi-fr-hi'`

And optionally try to add also `'hi-fr-en,en-fr,hi'` in the bt_steps.

**Comment by odel-odel** [comment]
Hi,
sorry for my misunderstanding...
I want unsupervised MT model so  I thought I can train my model based only on the file you have pretrain : mlm_tlm_xnli15_1024.pth, and no additional parallel/mono data.
Am I wrong ?

**Comment by odel-odel** [comment]
Can you also recommend on site with mono and parallel data for arabic language ?

**Comment by glample** [comment]
I would recommend looking at http://opus.nlpl.eu/ for the parallel data. For the monolingual data, that depends of the domain you want to translate, but Wikipedia in Arabic is pretty large I believe. Otherwise, there is common crawl but it's a bit more painful to download.
