### ISSUE TITLE
does batch size matter to performance

### ISSUE THREAD

**Issue by jind11** [facebookresearch/XLM#75]
hi, using single 12 GB GPU, I can only set the --tokens_per_batch to 1000 and the other settings are kept the same, but I can only get 29.xx bleu for en-fr on the test set, and this number will decrease as the number of epoch goes up. I am wondering whether the batch size or number of tokens per batch matter that much to the performance.

**Comment by glample** [comment]
Hi,

Yes, the batch size has a huge impact on the performance. The best is to have multi-GPU, where one GPU can process en-fr while another one processes fr-en, and to average the gradients. Overall, running a model on 8 GPU works much better than on 1. An alternative may be to accumulate the gradients on 1 GPU, but this is something that has to be implemented in the code.
