### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by sebastian-nehrdich** [facebookresearch/XLM#77]
Hello, 

I am currently trying to train on a rather small dataset (I have 400MB of Tibetan and 40MB of Sanskrit data). Training starts well, but after the first epoch (epoch 0) has finished, at the end of the evaluation (after about 10 minutes) it fails with the following error message: 

`/pytorch/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [17,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 305, in main
    scores = evaluator.run_all_evals(trainer)
  File "/home/basti/deeplearning/bilingual/XLM/src/evaluation/evaluator.py", line 176, in run_all_evals
    self.evaluate_mlm(scores, data_set, lang1, lang2)
  File "/home/basti/deeplearning/bilingual/XLM/src/evaluation/evaluator.py", line 291, in evaluate_mlm
    word_scores, loss = model('predict', tensor=tensor, pred_mask=pred_mask, y=y, get_scores=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/basti/deeplearning/bilingual/XLM/src/model/transformer.py", line 313, in forward
    return self.predict(**kwargs)
  File "/home/basti/deeplearning/bilingual/XLM/src/model/transformer.py", line 414, in predict
    masked_tensor = tensor[pred_mask.unsqueeze(-1).expand_as(tensor)].view(-1, self.dim)
`

Any idea what could be wrong? I suspect that maybe, there is some unknown word in the evaluation file, or maybe some lines in the eval files are too long. What do you think, where should I start to look for the error?

**Comment by sebastian-nehrdich** [comment]
This problem was indeed caused by a mistake with my inference data. It had some out-of-vocabulary tokens, after cleaning the files up everything went smoothly.

**Comment by PanXiebit** [comment]
I meet the same error,  at the end of the evaluation  it fails with the error message.

`/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [145,0,0], thread: [93,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [145,0,0], thread: [94,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [145,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "train.py", line 349, in <module>
    main(params)
  File "train.py", line 249, in main
    scores = evaluator.run_all_evals(trainer)
  File "/home/panxie/Document/XLM/src/evaluation/evaluator.py", line 243, in run_all_evals
    self.evaluate_mlm(scores, data_set, lang1, lang2)
  File "/home/panxie/Document/XLM/src/evaluation/evaluator.py", line 384, in evaluate_mlm
    word_scores, loss = model('predict', tensor=tensor, pred_mask=pred_mask, y=y, get_scores=True)
  File "/home/panxie/.conda/envs/pt-12/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/panxie/Document/XLM/src/model/transformer.py", line 328, in forward
    return self.predict(**kwargs)
  File "/home/panxie/Document/XLM/src/model/transformer.py", line 440, in predict
    masked_tensor = tensor[pred_mask.unsqueeze(-1).expand_as(tensor)].view(-1, self.dim)
RuntimeError: copy_if failed to synchronize: device-side assert triggered
`

I try to reclean my valid/test data, but the same error. Following is my preprocess method of dataset:
```
FASTBPE=tools/fastBPE/fast  # path to the fastBPE tool
OUTPATH=data/processed/TLM_en_fr/50k
mkdir -p $OUTPATH

# 1. download pretrained model, same bpe codes and vocab file
echo "!!!!! 1. load bpe codes and vocab !!!!!!!!!!"
wget -c https://dl.fbaipublicfiles.com/XLM/codes_enfr -P $OUTPATH
wget -c https://dl.fbaipublicfiles.com/XLM/vocab_enfr -P $OUTPATH

# 2. preprosses data
echo "!!!!! 2. Download and tokenize parallel data !!!!!!!!!!"
#./get-data-para.sh en-fr

head -1000000 data/para/en-fr.en.train >> $OUTPATH/train.en-fr.en.tok
head -1000000 data/para/en-fr.fr.train >> $OUTPATH/train.en-fr.fr.tok
cp data/para/en-fr.en.valid  $OUTPATH/valid.en-fr.en.tok
cp data/para/en-fr.fr.valid  $OUTPATH/valid.en-fr.fr.tok
cp data/para/en-fr.en.test  $OUTPATH/test.en-fr.en.tok
cp data/para/en-fr.fr.test  $OUTPATH/test.en-fr.fr.tok


# 3. build the training set for BPE tokenization (50k codes)
echo "!!!!! 3. Apply BPE tokenization on parallel corpora, and binarize using preprocess.py"
pair=en-fr
for lg in $(echo $pair | sed -e 's/\-/ /g'); do
        for split in train valid test; do
                $FASTBPE applybpe $OUTPATH/$split.$pair.$lg $OUTPATH/$split.$pair.$lg.tok $OUTPATH/codes_enfr
                python preprocess.py $OUTPATH/vocab_enfr $OUTPATH/$split.$pair.$lg
        done
done
```
I try to train tlm on the top of mlm, so I have to the provided bpe codes and vocab file.

Many answer about this error is that tokens in valid/test maybe out-of-vocabulary, but I process valid/test file use the same codes/vocab file.  What could be wrong?

**Comment by PanXiebit** [comment]
hi, I solve the problem by remove long sentence when valid/test. But I don't why long sentence could cause the error. I watch the nvidia-smi, obviously the memory of the gpu is enough. Could someone tell the reason?
