### ISSUE TITLE
XNLI-15 for Unsupervised Machine Translation

### ISSUE THREAD

**Issue by MaryaAI** [facebookresearch/XLM#78]
Can I use XNLI-15 for unsupervised machine translation or the current code is just supported for cross-lingual classifiers?
what about that "Pretrain a language model (with MLM)
The following script will pretrain a model with the MLM objective for English and French:"
can I use Arabic instead of French?

**Comment by aconneau** [comment]
XNLI-15 is meant for classification, not for UnsupMT. You can replace French by Arabic in the script yes.

**Comment by MaryaAI** [comment]
Thanks for clarification.

In https://github.com/facebookresearch/UnsupervisedMT   it was mentioned that I can enhance my model and make more efficient implementation of unsupervised machine translation.
So how I can improve my model by using this paper?  I can't use XNLI-15?
or can you give me the steps should I follow?

**Comment by glample** [comment]
XNLI-15 is probably not a model you want to use for machine translation, it was mainly designed for sentence classification and all the data was lowercased. However, if the target language you are interested in does not have casing (like, if you do English->Arabic) then this is probably fine. But it may be better to train a English-Arabic model from scratch with the MLM objective.
