### ISSUE TITLE
Imbalanced training data and when to stop training?

### ISSUE THREAD

**Issue by sebastian-nehrdich** [facebookresearch/XLM#81]
Hello, 

I have to questions at the moment:
1)How does XLM handle imbalanced datasets? For example, if I have 50M sentences of language a, but only 5M sentences of language b, will language a be overrepresented in the model? If so, what would be a good strategy to tackle this? 
2)I am training now about one day on a small dataset of 1M sentences in each language. How to know when to stop the training? Just try and see how the result is? I am now at epoch 37 and still continuing. Just observe until the precision is not increasing anymore?

**Comment by glample** [comment]
1) Yes, we have a strategy to sample more the languages that are more represented, check: https://github.com/facebookresearch/XLM/blob/e8a1b4b2173d0277ae5b9ce08ab9ea5831f5089c/src/utils.py#L292-L317 and https://github.com/facebookresearch/XLM/blob/e8a1b4b2173d0277ae5b9ce08ab9ea5831f5089c/src/utils.py#L361-L388
The parameter that handles this is `params.lg_sampling_factor`, by default it is equal to -1 which means that at each step a language is sampled randomly, so even a language presented 10x less will be sampled as much. If `params.lg_sampling_factor` is set to 1, a language will be sampled 10x more if it has 10x more sentences. For XNLI we use `params.lg_sampling_factor = 0.7`

2) Yes, in practice we usually train until the perplexity has basically converged, but sometimes we observe improvements on downstream tasks even after the model perplexity has stabilized, so I would suggest you keep training as long as possible if you can.

**Comment by sebastian-nehrdich** [comment]
thank you very much for the clarification, that makes sense to me!

**Comment by sebastian-nehrdich** [comment]
Just a quick follow-up on this: For example I have two rather big monolingual datasets (200mb each), but just a small parallel dataset (100k sentences). If I train from the very beginning mlm and tlm at the same time, will the model start to overfit on the tlm (because of just 100k sentences) while mlm has not yet converged? Would it be more wise to pretrain mlm for a while before training tlm then?

**Comment by glample** [comment]
You would indeed prevent overfitting by doing MLM for a while then TLM, but in that case you also have the risk that the model does not learn anything cross-lingual at all (depends on the language pair), and that the fine-tuning will not have enough data to do the alignment properly. So I don't know, I never experimented in that setting, you will have to try.
