### ISSUE TITLE
Regarding classification

### ISSUE THREAD

**Issue by sebastian-nehrdich** [facebookresearch/XLM#82]
Hi there, 

My model training has been quite successful, it is now giving very good results on nearest neighbor search as wel as UNMT. 
As a next step, I would like to do bilingual classification on my own data, e.g determining whether sentence B is a translation of A or not. I saw that the training-script allows a parameter called pc_steps but I am not sure what this is actually doing. What would be the place to start looking for? I saw some code in evaluation/xnli.py that looks like bilingual classification, is this where one should start?

**Comment by glample** [comment]
Hi,

I think the pc_step is doing exactly that, you can check: https://github.com/facebookresearch/XLM/blob/master/src/trainer.py#L634
If you call pc_step with `lang1,lang2`, the model will sample sentence pairs from this language pair, and learn to predict whether the two sentences in the pair are mutual translations, or if they are unrelated.

There is no official evaluation for this though. You can use the data in XNLI for evaluation, but XNLI has a slightly different purpose, and we did not implement anything to evaluate how well the model performs on this task. I guess you can use the code to train the model to do bilingual classification, but for evaluation you will need to implement something on top (should be quite straightforward to add that in `evaluator.py`).

**Comment by sebastian-nehrdich** [comment]
Great, worked like a charm, precision is absolutely stunning.
