### ISSUE TITLE
High CPU and memory  use on inference 

### ISSUE THREAD

**Issue by sebastian-nehrdich** [facebookresearch/XLM#83]
I observed that the CPU-load as well as the memory use on inference can be incredibly high. 
For example, when I predict similairty for about 1400 sentencepairs, memory use goes up to 25GB (when I clip the sequence length to max 200 characters per sentence). GPU seems to be barely used (use is indicated as 600mb, with 11GB idle - also the usage remains at 0%). Is this the expected behaviour? When I run the provided translation-script (translation.py), GPU is used as expected, this issue does not appear. 
I am using the following hacked-together scrip to infer sentence-similarity: 
https://pastebin.com/KbrvSzd4

**Comment by glample** [comment]
I'm not sure. Maybe can you try to add `del reloaded` after you do `model.load_state_dict(reloaded['encoder'])` and see if that helps. Did you try to investigate what line in particular in the code creates the high CPU usage?

**Comment by sebastian-nehrdich** [comment]
The problem was trivial. The code you gave as an example for the inference of the sentence embedding was designed to run on CPU only (I suppose to make it possible to test this while using the entire GPU for training). I used that as a base for the inference without understanding pytorch well enough to know that this is NOT utilizing the GPU. changing torch.LongTensor to torch.cuda.LongTensor as well as model = TransformerModel(params, dico, True, True) to model = TransformerModel(params, dico, True, True).cuda().eval() did the trick!
Now inference utilizes the GPU to the full extent.
