### ISSUE TITLE
Can't Download XNLI

### ISSUE THREAD

**Issue by simonefrancia** [facebookresearch/XLM#89]
Cannot run this command:
```wget -c https://dl.fbaipublicfiles.com/XNLI/XNLI-1.0.zip```
Forbidden Error

**Comment by tnq177** [comment]
same here, i gotta use these instead ``https://www.nyu.edu/projects/bowman/xnli/XNLI-MT-1.0.zip``, ``https://www.nyu.edu/projects/bowman/xnli/XNLI-1.0.zip``.
