### ISSUE TITLE
Question about XLM unsupervised NMT stopping criterion

### ISSUE THREAD

**Issue by Alex-Fabbri** [facebookresearch/XLM#94]
In the Phrase-Based and NUMT paper there are two model selection procedures described, the unsupervised "round-trip" criterion and cross-validation with a small parallel corpus. These functions are  [eval_back](https://github.com/facebookresearch/UnsupervisedMT/blob/master/NMT/src/evaluator.py#L182) and [eval_para](https://github.com/facebookresearch/UnsupervisedMT/blob/master/NMT/src/evaluator.py#L125) respectively in the PB-NUMT codebase. 

The analogous function in this codebase is [evaluate_mt](https://github.com/facebookresearch/XLM/blob/master/src/evaluation/evaluator.py#L325), which on quick inspection seems to be the eval_para function. Is it correct then that model selection for this paper is done only using cross validation on the small parallel corpus and not using the unsupervised criterion?

**Comment by glample** [comment]
Yes, you are correct. Using the small validation set or the "round-trip" did not make a big difference, so we ended up using the small validation set for simplicity.

**Comment by Alex-Fabbri** [comment]
Makes sense, thanks for the response!
