### ISSUE TITLE
Do you plan on releasing an MLM model trained on monolingual data from all 15 languages?

### ISSUE THREAD

**Issue by Akella17** [facebookresearch/XLM#96]
The paper suggests the use of an MLM model on XNLI task (Table 1). Can you release this model as well? An MLM model trained only on 15 languages without any parallel data performs comparably to an MLM+TLM trained on all 15 languages (Table 1).

We need this MLM model for our research in multilingual unsupervised NMT.

**Comment by glample** [comment]
The MLM only model is now available here: https://dl.fbaipublicfiles.com/XLM/mlm_xnli15_1024.pth
