### ISSUE TITLE
About Monolingual data

### ISSUE THREAD

**Issue by zhang-jinyi** [facebookresearch/XLM#98]
Hi, 
I have a question about Monolingual data.

```
===== Data summary
Monolingual training data:
    en: ./data/processed/en-fr/train.en.pth
    fr: ./data/processed/en-fr/train.fr.pth
Monolingual validation data:
    en: ./data/processed/en-fr/valid.en.pth
    fr: ./data/processed/en-fr/valid.fr.pth
Monolingual test data:
    en: ./data/processed/en-fr/test.en.pth
    fr: ./data/processed/en-fr/test.fr.pth
Parallel validation data:
    en: ./data/processed/en-fr/valid.en-fr.en.pth
    fr: ./data/processed/en-fr/valid.en-fr.fr.pth
Parallel test data:
    en: ./data/processed/en-fr/test.en-fr.en.pth
    fr: ./data/processed/en-fr/test.en-fr.fr.pth
```
After preprocessing, we could get this summary, and in the [get-data-nmt.sh](get-data-nmt.sh) file , there are
```
ln -sf $PARA_SRC_VALID_BPE.pth $SRC_VALID_BPE.pth
ln -sf $PARA_TGT_VALID_BPE.pth $TGT_VALID_BPE.pth
ln -sf $PARA_SRC_TEST_BPE.pth  $SRC_TEST_BPE.pth
ln -sf $PARA_TGT_TEST_BPE.pth  $TGT_TEST_BPE.pth
``` 
Monolingual validation and test data are parallel validation and test data. My question is, what is the meaning of separation of the monolingual and parallel (validation and test) data? What is the use of these monolingual (validation and test) data, and these monolingual (validation and test) data were used during the training or not?

This helps to understand the code, thank you in advance.

**Comment by glample** [comment]
Hi,

When the code loads data, it always loads 3 splits of train/valid/test data. For training BERT, this is important to have monolingual validation data to check that there is no overfitting. For unsupervised MT, monolingual validation and test data are kind of useless, as monolingual data is only used to generate back-translated sentences with the training set. The monolingual validation data could be used to compute the source -> target -> source round trip BLEU, but in practice they are not used at all as far as I remember.

**Comment by zhang-jinyi** [comment]
Thank you very much!

**Comment by conquerSelf** [comment]
> Hi,
> 
> When the code loads data, it always loads 3 splits of train/valid/test data. For training BERT, this is important to have monolingual validation data to check that there is no overfitting. For unsupervised MT, monolingual validation and test data are kind of useless, as monolingual data is only used to generate back-translated sentences with the training set. The monolingual validation data could be used to compute the source -> target -> source round trip BLEU, but in practice they are not used at all as far as I remember.

Hello,I have another question about preprocessing the mono data:
echo "Applying BPE to valid and test files..."
$FASTBPE applybpe $PARA_SRC_VALID_BPE $PARA_SRC_VALID $BPE_CODES $SRC_VOCAB
$FASTBPE applybpe $PARA_TGT_VALID_BPE $PARA_TGT_VALID $BPE_CODES $TGT_VOCAB
$FASTBPE applybpe $PARA_SRC_TEST_BPE  $PARA_SRC_TEST  $BPE_CODES $SRC_VOCAB
$FASTBPE applybpe $PARA_TGT_TEST_BPE  $PARA_TGT_TEST  $BPE_CODES $TGT_VOCAB

As the above code,why do you need reference the source vocalbulary $SRC_VOCAB when you exHi,
> 
> When the code loads data, it always loads 3 splits of train/valid/test data. For training BERT, this is important to have monolingual validation data to check that there is no overfitting. For unsupervised MT, monolingual validation and test data are kind of useless, as monolingual data is only used to generate back-translated sentences with the training set. The monolingual validation data could be used to compute the source -> target -> source round trip BLEU, but in practice they are not used at all as far as I remember.

Hello,I have another question about preprocessing the mono data:
echo "Applying BPE to valid and test files..."
$FASTBPE applybpe $PARA_SRC_VALID_BPE $PARA_SRC_VALID $BPE_CODES $SRC_VOCAB
$FASTBPE applybpe $PARA_TGT_VALID_BPE $PARA_TGT_VALID $BPE_CODES $TGT_VOCAB
$FASTBPE applybpe $PARA_SRC_TEST_BPE  $PARA_SRC_TEST  $BPE_CODES $SRC_VOCAB
$FASTBPE applybpe $PARA_TGT_TEST_BPE  $PARA_TGT_TEST  $BPE_CODES $TGT_VOCAB

As the above code,why do you need reference the source vocalbulary $SRC_VOCAB or target vocalbulary $TGT_VOCAB when you execuate the 'applybpe' command?Thank you so much!
